### ISSUE TITLE
Using model.becomes(another_model)

### ISSUE THREAD

**Issue by klaussk8** [globalize/globalize#130]
Hi,

Congratulations for the awesome gem, I just found a bug when using following code:

``` ruby
a = Model.new(params[:model])
# before becomes, the translates field have some content
a = a.becomes(AnotherChildModel)
```

After that, the content of the translates field got nil, where:

``` ruby
class Model < ActiveRecord::Base
  translates :field
end

class AnotherChildModel < Model
end
```

**Comment by TruffeCendree** [comment]
Hello, I am meeting the exact same behaviour.

It seems that the `a.globalize` identity is not preserved on the casted entity (defined at /lib/globalize/active_record/instance_methods.rb:7).
