### ISSUE TITLE
Removing translated attribute breaks table creation migration

### ISSUE THREAD

**Issue by viseztrance** [globalize/globalize#131]
Hi,

It looks to me that once a translation table has been created there's no way of removing or changing an attribute. Doing so will throw `Missing translated field :removed_field`, because the field is no longer in the model as a translation option.

The only workaround I see is to edit the migration directly, or create a new one, but never be able to run all the migrations from zero which is pretty bad.

Perhaps only a warning is enough rather than raising an exception. I would be happy to have a look over the code and submit a patch, should this be the answer.

**Comment by poudelmadhav** [comment]
> I found a workaround I explain in this gist https://gist.github.com/3487849
> 
> It would be quite simple to take this idea and create a pull request, but as it modifies the behaviour of the migrations and could affect migrations from other projects it must be optional (maybe an :only_this_fields option).
> 
> If you find this interesting I can find the time to develope it and do the pull request :)

This worked for me. Thanks.
