### ISSUE TITLE
Add support for non-string types

### ISSUE THREAD

**Issue by dorner** [globalize/globalize#187]
We are using globalize in two separate systems - one is the production system, where text is displayed; but we are also using it to enter that data, in an admin system. I added some magic functions to make this easier (e.g. for forms), but ran into a wall when I realized there is a shortcoming in the design.

We want to globalize not only string fields, but to allow us to store arbitrary fields per language. For example, there is a list of items (integer) in a flyer for each language. I'd like to be able to get/set that value per language using globalize3's functionality (i.e. number of English items, number of French items, etc.). We also have fields indicating when a piece of work is completed in each language (datetime). However, right now it seems that it only supports the :text and :string types. Is there anything in the design of globalize3 that would require this? What string-specific functionality is there?

I saw this pull request https://github.com/svenfuchs/globalize3/pull/116  but saw it was declined due to the use case not being valid. I hope this one is better described. 8-)

**Comment by jamesneve** [comment]
+1
Is this still a likely feature to come out anytime in the near future? Like other people, I'm also having to use a rather awkward hack to make it work.

**Comment by vizo** [comment]
:+1:

**Comment by vizo** [comment]
I also need to save different longitude, latitude per language.

@jamesneve can you please show your hack?

**Comment by slavajacobson** [comment]
Still nothing? :(

**Comment by vizo** [comment]
It worked for me ....

You can do initializer globalize_override.rb and put inside:
```
module Globalize
  module ActiveRecord
    module Migration
      Migrator.class_eval do
        def valid_field_type?(name, type)
          # Allow translation of any type of field
          !translated_attribute_names.include?(name) || true # || [:string, :text].include?(type)
        end
      end
    end
  end
end

```

**Comment by Dschee** [comment]
Thank you @vizo, I have just filed a pull requests that tries to fix this issue using your approach (by just allowing other types). My idea was to create a new feature branch named `non_charbased_type_support` but I couldn't find a way to create a new branch within a pull requests so the maintainers will need to do some manual work to merge that the intended way.

Once the feature branch is created, the feature could be tried out just by adding this to the Gemfile:
`gem 'globalize', github: "globalize/globalize', branch: 'feature/non_charbased_type_support'`

I hope this helps getting things started with this issue.

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289193/b888a334-4367-11e5-98a2-47387e3555cd.jpg)
Try Createer.com. You can easily design online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned template (look here https://beta2.createer.com/Templates) s and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment.

**Comment by ncri** [comment]
Just came across this issue when noticing that my translated boolean fields behave oddly:

```
m = MyModel.new
m.translated_boolean = false
m.translated_boolean 
=> nil   # should be false!
```

**Comment by ncri** [comment]
This patch fixes my issue:

```
module Globalize
  module ActiveRecord
    module InstanceMethods
      def read_attribute(name, options = {})
        options = {:translated => true, :locale => nil}.merge(options)
        return super(name) unless options[:translated]

        if translated?(name)
          val = (value = globalize.fetch(options[:locale] || Globalize.locale, name))
          unless val.nil?
            value
          else
            super(name)
          end
        else
          super(name)
        end
      end
    end
  end
end
```

```
m = MyModel.new
m.translated_boolean = false
m.translated_boolean 
=> false   # correct
```

Don't know yet if it has any unwanted side effects. ;-)

**Comment by parndt** [comment]
@ncri if we change the core implementation then our tests are a pretty good indication, if you were to open a PR? 👍

**Comment by parndt** [comment]
Is the issue fixed by #579 ?

**Comment by ncri** [comment]
I don't think so, both patches are needed. I made mine for boolean fields but it shouldn't affect other fields negatively. We run it in production for many months now. I hope to find the time to setup globalize for development and see if the tests pass. I can then make a PR.

**Comment by parndt** [comment]
Thanks @ncri

**Comment by ncri** [comment]
https://github.com/globalize/globalize/pull/589

**Comment by ncri** [comment]
Looks like my pull request might not be necessary as I couldn't reproduce my boolean issue with the lastest globalize code. 

Now, even without my patch boolean attribute retrieval works correctly:

```
m = MyModel.new
m.translated_boolean = false
m.translated_boolean 
=> false   # correct
```

I still want to make some more tests, in case my fix was needed for a special case I wasn't able to reproduce yet.

**Comment by ncri** [comment]
Sorry about this, my issue has been fixed already quite a while ago here: 

https://github.com/globalize/globalize/pull/589/commits/a95c671234b24825fe092adeb5431297cfe81618

So I think this issue here can be closed now.
