### ISSUE TITLE
Globalize.locale remaining set over different sessions

### ISSUE THREAD

**Issue by gaganawhad** [globalize/globalize#224]
When I set `Globalize.locale`, it is remains set even over different sessions when using  webservers like thin and unicorn. I am guessing this is unintentional behavior. 

This seems related to this issue: https://github.com/rails/rails/issues/8517 and whats seems to be recommended is "cleaning up the Thread". 

Is this something that needs to be looked into? Let me know if I can help.

**Comment by bitboxer** [comment]
Any update on this?

**Comment by gaganawhad** [comment]
Hey @bitboxer, sorry I didn't get to this. Not sure that I can anytime soon... :(
