### ISSUE TITLE
.dup does not duplicate translated fields

### ISSUE THREAD

**Issue by the8472** [globalize/globalize#234]
If you dup an AR object it does retain its attributes. If you dup a translated object this does not work for the translated fields because they're stored in a relation and those don't get copied by dup.

This makes the transition from untranslated fields to translated ones less seamless in my opinion.

**Comment by scarfacedeb** [comment]
I suppose, we could close this one, because #317 fixed it? @parndt

**Comment by simi** [comment]
Yup.
