### ISSUE TITLE
Is it possible to use custom scopes?

### ISSUE THREAD

**Issue by rvrm** [globalize/globalize#239]
I'm trying to add a custom scope to enable users to have their own translations within the translations table:
http://stackoverflow.com/questions/16841599/i18nbackendactiverecord-with-scope

Can anyone think of a simple solution for this. Thanks for your help!

**Comment by scarfacedeb** [comment]
@rvrm If it's still relevant: you could reopen Translation model class and add any new scopes that you want in it.
e.g. for translated Page model, you'll need to reopen `Page::Translation` model in `app/models/page/translation.rb`:
```ruby
class Page::Translaction < ::Globalize::ActiveRecord::Translation
  self.abstract_class = true
  scope :for_user, -> (user_id) {  where(user_id: user_id) }
end
```

**Comment by simi** [comment]
I think this can be closed @scarfacedeb.

**Comment by scarfacedeb** [comment]
@simi I didn't want to close it without trying to provide some kind of answer first.

**Comment by simi** [comment]
Actually this is not an issue, but a question and you've provided a good answer. So I think it is solved. :confetti_ball: :
