### ISSUE TITLE
Calling attribute_changed?

### ISSUE THREAD

**Issue by yannp** [globalize/globalize#240]
Globalize don't seem to support dynamic methods from activemodel/lib/active_model/dirty.rb like:

``` ruby
post.content_changed?  # => true
```

It seems possible to do it as 'translated_attributes' contains the old attributes value.

Any advice on how to start implementing this?

Thanks.

**Comment by hmakcheer** [comment]
Any progress made on this?

**Comment by scarfacedeb** [comment]
@hmakcheer I plan to look into it in a week or two

**Comment by hmakcheer** [comment]
Thanks. In the meantime if anyone was interested in getting the previous value of a translated attribute:

```ruby
previous_content = post.changes.include?("content") if post.changed?
```

**Comment by hoverbird** [comment]
Bump... not only does this break detecting whether a given attribute has actually been changed in the default_locale, for me... it also loses the value before being changed.
