### ISSUE TITLE
Behavior for translated attributes when the parent table includes translated columns

### ISSUE THREAD

**Issue by gaganawhad** [globalize/globalize#245]
I have a Model, say Post, that has the two translated fields, title and content. The database table for the Post model  has both the columns title and content, which are also in the post_translations table. This setup is a default result of having an app set-up on a locale and then adding a migration that adds the translations table, with the columns that will be translated. 

So the schema would look something like this: 

``` ruby
  create_table :posts, :force => true do |t|
    t.string     :title
.
.
.
  end

  create_table :post_translations, :force => true do |t|
    t.string     :locale
    t.references :post
    t.string     :title
.
.
.
  end
```

My first question is, is this setup supported by globalize3 ? If its not supported, should I be deleting those columns from my parent model after migrating data to the translations table? And if so, should add a note on the README page ? 

If this is schema supported, then the current master isn't doing it what I expect to in this test: 

``` ruby
  test 'return nil when a translated attribute is set as nil when no fallbacks set up' do
    post = Post.create(:title => 'title',  :locale => :en)
    post.update_attributes(:title => nil, :locale => :de)

    post = Post.first
    assert_equal post.title, 'title'

    Globalize.locale = :de
    assert_equal nil, post.title
  end
```

I have the test and the schema set up in this commit: https://github.com/gaganawhad/globalize3/commit/8ea9c9cbe1863745ce5b233ec5b7fa73922ea626

Is there something I am missing  ?

**Comment by prusswan** [comment]
What was the conclusion? I would prefer to fallback to the parent column, so that the parent table remains usable even when the translations table is broken/missing

**Comment by parndt** [comment]
We now don't refer back to the parent table's columns at all.
