### ISSUE TITLE
Missing translated field issue

### ISSUE THREAD

**Issue by etagwerker** [globalize/globalize#264]
Hello,

I just renamed a column that is being translated and after resetting my database I am getting this error:

```
Missing translated field :eyeware/Users/etagwerker/.rvm/gems/ruby-1.9.3-p327@well/gems/globalize3-0.3.0/lib/globalize/active_record/migration.rb:124:in `block in validate_translated_fields'
/Users/etagwerker/.rvm/gems/ruby-1.9.3-p327@well/gems/globalize3-0.3.0/lib/globalize/active_record/migration.rb:123:in `each'
/Users/etagwerker/.rvm/gems/ruby-1.9.3-p327@well/gems/globalize3-0.3.0/lib/globalize/active_record/migration.rb:123:in `validate_translated_fields'
/Users/etagwerker/.rvm/gems/ruby-1.9.3-p327@well/gems/globalize3-0.3.0/lib/globalize/active_record/migration.rb:30:in `create_translation_table!'
/Users/etagwerker/.rvm/gems/ruby-1.9.3-p327@well/gems/globalize3-0.3.0/lib/globalize/active_record/migration.rb:12:in `create_translation_table!'
```

My model used to look like this:

```
class Plan < ActiveRecord::Base  
  translates :eyeware
```

but now looks like this:

```
class Plan < ActiveRecord::Base  
  translates :eyewear
```

I realize that there is something wrong in the way that I changed the column name. 

What is the best way to change a translateable column name? 

I guess that by just changing the name in the `translates` statement and adding a migration with `rename_column` is not enough.

Thanks!

**Comment by twoneks** [comment]
@parndt I'm not sure your suggested solution is the solution. In my case i modified the model removing some translated fields, and in a later migration I remove from those fields from the `my_table_translations`, if I do modify the previous migration as you said, I wont be able to execute the migration that removes those columns, and so I can't execute all the migrations. My local env will diverge from my production env. Did anybody face this problem?

**Comment by parndt** [comment]
> I wont be able to execute the migration that removes those columns

It's 7 years ago but, from memory, for this stuff I used to write migrations that checked the state of the database before doing operations like this, so you could check to see if the columns were removed already.
