### ISSUE TITLE
ActiveRecord::Relation patch breaks building of relations with conditions

### ISSUE THREAD

**Issue by the8472** [globalize/globalize#288]
The update from 0.3.0 to 0.3.1 broke building instances of relations that have conditions. Normally rails would build pre-fill all attributes with the conditions to ensure the created record will match the association.
After the update it creates a blank object instead

I'm not sure whether this is a conflict between patches from squeel[1] and globalize[2], but requiring squeel after globalize so that its patch applies last seems to work.
It's also possible that relation building is broken with vanilla rails 3.2.x.

[1] https://github.com/ernie/squeel/blob/master/lib/squeel/adapters/active_record/relation_extensions.rb#L397-406
[2] https://github.com/globalize/globalize/blob/v0.3.1/lib/patches/active_record/relation.rb#L4-12

**Comment by itschn** [comment]
1+

**Comment by DmitrySharikov** [comment]
+

**Comment by akrisanov** [comment]
Ruby 2.3.3
Rails 4.2.8
PostgreSQL 9.6.3

Have the same problem:

```
 category = Category.last
  Category Load (0.7ms)  SELECT  "categories".* FROM "categories"  ORDER BY "category_translations"."name" DESC LIMIT 1
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "category_translations"
LINE 1: ...ELECT  "categories".* FROM "categories"  ORDER BY "category_...
                                                             ^
: SELECT  "categories".* FROM "categories"  ORDER BY "category_translations"."name" DESC LIMIT 1
from /Users/akrisanov/.rvm/gems/ruby-2.3.3@optisure/gems/activerecord-4.2.8/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
```
