### ISSUE TITLE
Globalize breaks `where.not` query

### ISSUE THREAD

**Issue by leschenko** [globalize/globalize#320]
`Product.where.not(id: [1, 2]).to_sql` produce 
`SELECT`products`.* FROM`products`WHERE (NOT ('---\n:id:\n- 1\n- 2\n'))` sql

**UPDATE:**
This bug exists only when [squeel](https://github.com/activerecord-hackery/squeel) gem used

**Comment by viniciusnz** [comment]
I also needed to change

`if opts == :chain`

 to

`if ((opts == :chain) and (not block_given?))`

See https://github.com/viniciusnz/globalize/commit/23301274e9dcacc3e8eaea1db0984e3fd8ec944b

I don't know if I couldn't load squeel and globalize at the right order and whether that was the problem, but with both I couldn't get a simple `Model.where{attribute == value}.to_sql` to work, on the models where globalize was translating (models without translation continued to work fine.

I noticed there was the block_given override at squeel, but not at globalize, and noticed that globalize was calling super to squeel, not the other way around. I tried inverting their order at the gemfile and even using required: false on squeel and later loading it, without success to invert the chain.

Please note that squeel will not be able to access the globalize translated attributes, but I'm happy to use regular queries for those attributes.

I hope this helps someone...
