### ISSUE TITLE
Is there a way to use accepts_nested_attributes_for with null: false columns?

### ISSUE THREAD

**Issue by scarfacedeb** [globalize/globalize#325]
I'm working on a plugin for rails_admin: https://github.com/scarfacedeb/rails_admin_globalize_field and I'm having an issue with `null: false` columns (without default value) in translations tables.

I can successfully add/update records from rails_admin, because I'm submitting translations using nested attributes (e.g. artwork[translations][title]) and activerecord process them as any ordinary association.

But now I can't save the records using generated globalize methods. (e.g. artwork.title=; see example below)

Relevant migration code:

``` ruby
Artwork.create_translation_table! title: { type: :string, null: false }
```

Model code:

``` ruby
translates :title
accepts_nested_attributes_for :translations, allow_destroy: true
```

And console output:

``` ruby
> Artwork.create({ title: "test", category_id: 1, image: "file.jpg"  })
(0.2ms)  BEGIN
SQL (0.6ms)  INSERT INTO "artworks" ("category_id", "created_at", "image", "slug", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["category_id", 1], ["created_at", Sat, 25 Jan 2014 08:28:43 UTC +00:00], ["image", "file.jpg"], ["slug", "1"], ["updated_at", Sat, 25 Jan 2014 08:28:43 UTC +00:00]]
SQL (1.8ms)  INSERT INTO "artwork_translations" ("artwork_id", "created_at", "locale", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["artwork_id", 100], ["created_at", Sat, 25 Jan 2014 08:28:43 UTC +00:00], ["locale", "en"], ["updated_at", Sat, 25 Jan 2014 08:28:43 UTC +00:00]]
PG::NotNullViolation: ERROR:  null value in column "title" violates not-null constraint
(0.2ms)  ROLLBACK
```

---

I understand that a reason behind it is that `accepts_nested_attributes_for :translations` sets `autosave` association option to **true** and it forces activerecord to save empty associations when I'm saving parent record.
I figured that globalize uses `after_create` callbacks with `autosave: false` by default and `accepts_nested_attributes_for` breaks the save logic, but I need to add/edit multiple translations at once (hence `accepts_nested_attributes_for`).

---

I came up with a workaround to reset `autosave` option, when I'm creating records using generated methods, instead of `translations` association.
But it doesn't seem right and I don't want to put it into production.

``` ruby
before_create :reset_autosave
  def reset_autosave
    if self.globalize.stash.any? { |key, value| !value.empty? }
      assoc = self.class.reflect_on_association(:translations)
      assoc.options[:autosave] = false
    end
    true
  end
```

Another option is to provide default values for `null:false` columns, but it means that I can't have database-level validation for presence.

---

Does anybody have any thought about my situation?

**Comment by mustmodify** [comment]
@scarfacedeb would you mind posting a gist-or-README-addition showing model and views (and presumably controller for completeness) of how to add forms for languages? I'm digging in but the water seems ... wait, this metaphor isn't getting off the ground. Anyway, I'm just getting started and it seems oddly complex relative to other things. This should be easier.

**Comment by scarfacedeb** [comment]
@mustmodify sorry, It was a loong time ago and I no longer use this gem anywhere.

I guess you could take a look at [rails_admin_globalize_field](https://github.com/scarfacedeb/rails_admin_globalize_field) to get some inspiration.
