### ISSUE TITLE
Add option to skip overriding `relation` method

### ISSUE THREAD

**Issue by leschenko** [globalize/globalize#326]
Can we make this https://github.com/globalize/globalize/blob/master/lib/globalize/active_record/class_methods.rb#L66 optional?

**Comment by OpakAlex** [comment]
@leschenko  any progress?)

**Comment by leschenko** [comment]
Workaround is still in business :sunglasses:
```ruby
Globalize::ActiveRecord::ClassMethods.module_exec do
  def relation
    super
  end
end
```
