### ISSUE TITLE
Can not .delete_all when querying on translated attributes

### ISSUE THREAD

**Issue by masv** [globalize/globalize#327]
I have run into a problem with `.delete_all` on ActiveRecord models when a translated attribute is included in the conditions.

On a regular `.where` Globalize will include the translated field and the translations table correctly in the SQL query, but with `.delete_all` only the field is added to the query, not the table, and the query ends up looking like this:

``` sql
DELETE FROM "posts"
WHERE "post_translations"."title" = 'title 1'
  AND "post_translations"."locale" = 'en'
  AND (post_translations.title IS NOT NULL)
```

This happens regardless of wether `.delete_all` is chained to an existing relation or conditions are passed directly to `.delete_all`.

I have created failing test cases for both scenarios here: https://github.com/masv/globalize/commit/f4789d90ffef540261b2b3ee4439c2f64ec58298

Is this something that should be fixed, or can you suggest a workaround? I wouldn't mind taking a stab at fixing it, but I want to know if you have any ideas before I get started.

**Comment by basex** [comment]
is it expected to have update_all working one day for translated attributes?

**Comment by ridiculous** [comment]
What about just calling update_all on the translation model itself?
```ruby
FatModel::Translation.where(fat_model_id: 1).update_all(updated_at: Time.now)
```
