### ISSUE TITLE
rake db:migration problem

### ISSUE THREAD

**Issue by dlamichhane** [globalize/globalize#344]
For example I have the following class with the title and test attributes

```
class Post < ActiveRecord::Base
  attr_accessible :title, :text
  translates :title, :text
end
```

And based on the above class I have the following migration

```
class CreatePosts < ActiveRecord::Migration
  def change
    create_table :posts do |t|
      t.text :text
      t.title :string
      t.timestamps
    end
  end
end
```

Based on the above class Post, I have created the translation table

```
class TranslatePosts < ActiveRecord::Migration
  def self.up
    Post.create_translation_table!({
      :title => :string,
      :text => :text
    }, {
      :migrate_data => true
    })
  end
  def self.down
    Post.drop_translation_table! :migrate_data => true
  end
end
```

Till now everything is fine. Now at this situation I thought of removing the title column from the post table. Therefore I removed the title attributes from the class Post and used the below migration to remove the title column from the posts table and post_translations table. Since I am removing the title column from the posts table and  post_translations table and it is obvious to remove them through the Post class too. Now the Post class looks like this

```
class Post < ActiveRecord::Base
  attr_accessible :text
  translates :text
end
```

And the migration to remove the title column looks like this

```
class RemoveTitleFromPosts < ActiveRecord::Migration
  def up
    change_table :posts do |t|
      t.remove :title
    end

    change_table :post_translations do |t|
      t.remove :title
    end
  end

  def down
    change_table :posts do |t|
      t.string :title
    end

    change_table :post_translations do |t|
      t.string :title
    end
  end
end
```

At this situation, when I run the migration command
`rake db:migration`
I got the error like this

```
An error has occurred, this and all later migrations canceled:
Missing translated field :title/home/dlamichhane/.rvm/gems/ruby-2.0.0-p247@blog/gems/globalize-3.1.0/lib/globalize/active_record/migration.rb:139:in `block in validate_translated_fields'
```

And the error is raised in the migration because I had removed the "tittle" attributes from the translates section of the Post class but the TranslatePosts migration still have the ":title => :string". And it seems the migration is dependent in the class attributes

**Comment by dbrunst** [comment]
I had a similar problem when I later renames a column in a translated table.

**Comment by ridiculous** [comment]
What if you drop the translation column _before_ the posts column?
