### ISSUE TITLE
Test error "table xxx has no column named yyy"

### ISSUE THREAD

**Issue by mcmegavolt** [globalize/globalize#347]
Hi there!
How to make fixtures for my tests?
When I try to set translated columns of table got "test error, has no column"
I have no original columns that have translations...
Is there solution for that?
Thanks!

**Comment by dongli** [comment]
I still do not know how to write a fixture for a model that has translated columns.

**Comment by firedev** [comment]
@dongli Use [`globalize-acessors`](https://github.com/globalize/globalize-accessors) and write fixtures as if the localized colums are in the same table.

**Comment by dongli** [comment]
@firedev Thanks! But I encountered the following error after add `globalize-accessors` gem in my Rails 4 app:
```
undefined local variable or method `globalize_accessors' for #<Class:0x007ffcd9e99728>
```

**Comment by firedev** [comment]
@dongli Somehow I am using it with the latest Rails 4 myself so it should work. Put `globalize_accessors` after `translates` in model.

**Comment by krisdigital** [comment]
Correct way of doing it with fixtures can be seen here: http://stackoverflow.com/a/32138229/965686

Summary:

The translation model's class is `YourModel::Translation`, so you have to put the fixture in the folder 'your_model' to reflect that.

The association name for any translated model is `globalized_model`, so you have to use that property in your fixture, too.
