### ISSUE TITLE
Validate uniqueness of globalized field, by locale

### ISSUE THREAD

**Issue by fmenegoni** [globalize/globalize#358]
Hi,
is there a way to validate uniqueness of globalized field, scoped with `:locale`? 
my environment:
rails 4.1.1
ruby 2.1.1
globalize 4.0.1
I need something like:

``` ruby
validates :slug, uniqueness: {scope: :locale}
```

where `:slug` is a translated attribute
thanks

**Comment by ppfp** [comment]
How can it be done with globalize 5? 

I tried:
```
validates_associated :translations
translation_class.validates :label, uniqueness: true
```

But it throws an error on even when `label` is unique.

**Comment by obahareth** [comment]
@ppfp Did you ever come up with a solution? Still struggling with this.

**Comment by phlegx** [comment]
Please check my solution: http://stackoverflow.com/a/35234221/132235
**Feedback welcome!**

**Comment by PragmaticEd** [comment]
A bit late to the party, but wanted to share my solution, which i think is the nicest looking.

Add to `app/models/validators`:
```ruby
class TranslationUniquenessValidator < ActiveModel::EachValidator

  def validate_each(record, attribute, value)
    record.translations.each do |t|

      if options[:scope] == :locale
        records = t.class.where("locale = '#{t.locale.to_s}' AND #{attribute} = '#{t[attribute]}'").count
      else
        records = t.class.where("#{attribute} = '#{t[attribute]}'").count
      end

      record.errors.add("#{attribute}_#{t.locale}", options[:message] || :uniqueness) unless records.zero?
    end
  end

end
```

Then in model you can do this:

```ruby
validates :title, translation_uniqueness: {scope: :locale, message: 'custom message'}
```

Option `scope: :locale` just specifies if uniqueness should be in one locale. If it should be uniq across all languages, just remove that option completely.

Ofc `:message` is not required. It will use default message for uniqueness .
