### ISSUE TITLE
An article about Globalize

### ISSUE THREAD

**Issue by bodrovis** [globalize/globalize#375]
Hello and thanks for this great gem!

Recently I've written an article about I18n and Globalize for Sitepoint (http://www.sitepoint.com/go-global-rails-i18n/) - this is a guide on how to tie this all together (as well as adding functionality to change the locale) so maybe you'd want to put that link somewhere so that users of the gem could see some working example.

**Comment by simi** [comment]
Really nice article @bodrovis! We will link it in README in #416.
