### ISSUE TITLE
The translations order is not ensured

### ISSUE THREAD

**Issue by jdevega** [globalize/globalize#383]
In production environment, when I am recovering translations for a model, the translations are sorted in reverse order, so the first translation is always returned instead of last one. It's not happening with other models. Is there any way to ensure translations return translations sorted by created_at DESC ?

2.1.2 :004 > Course.find(9).translations.where(:locale => 'es').map{|t| [t.created_at, t.id]}
 => [[Wed, 05 Nov 2014 10:13:00 UTC +00:00, 78], [Wed, 05 Nov 2014 10:14:56 UTC +00:00, 80], [Wed, 05 Nov 2014 10:15:56 UTC +00:00, 82], [Wed, 05 Nov 2014 10:16:14 UTC +00:00, 84], [Wed, 05 Nov 2014 10:18:00 UTC +00:00, 86], [Wed, 05 Nov 2014 10:20:04 UTC +00:00, 88], [Wed, 05 Nov 2014 10:22:19 UTC +00:00, 90], [Wed, 05 Nov 2014 11:12:57 UTC +00:00, 92], [Wed, 05 Nov 2014 11:43:36 UTC +00:00, 94], [Wed, 05 Nov 2014 12:03:27 UTC +00:00, 96], [Wed, 05 Nov 2014 12:28:10 UTC +00:00, 114], [Wed, 05 Nov 2014 12:28:34 UTC +00:00, 116], [Wed, 05 Nov 2014 15:39:13 UTC +00:00, 134], [Wed, 05 Nov 2014 15:46:03 UTC +00:00, 142], [Fri, 07 Nov 2014 10:16:04 UTC +00:00, 144], [Fri, 07 Nov 2014 10:16:17 UTC +00:00, 146], [Fri, 07 Nov 2014 10:20:08 UTC +00:00, 148], [Fri, 07 Nov 2014 10:21:29 UTC +00:00, 150]]
2.1.2 :005 > Course::Requirement.first.translations.where(:locale => 'es').map{|t| [t.created_at, t.id]}
 => [[Fri, 07 Nov 2014 10:22:45 UTC +00:00, 6], [Thu, 06 Nov 2014 18:43:28 UTC +00:00, 4], [Fri, 31 Oct 2014 12:52:34 UTC +00:00, 2]]

**Comment by scarfacedeb** [comment]
You can call default_scope on `translation_class` inside a model:
```ruby
translates :title, :body
translation_class.default_scope -> { order("page_translations.created_at DESC") } 
```

But usually it's a bad practice to use default scope, so instead you can add another has_many association:
```ruby
has_many :sorted_translations, -> { order(created_at: :desc) }, class_name: Page::Translation
```
