### ISSUE TITLE
Validation errors associated on translated attributes including locale

### ISSUE THREAD

**Issue by phlegx** [globalize/globalize#386]
Hi!

**Rails:** 4.1.7
**Globalize:** 4.0.2
**Globalize Accessors:** 0.1.5

I want to translate category names for all available locales in one view. I use gem globalize-accessors for this purpose. So I can use in my form:

```ruby
f.text_field :name_en
f.text_field :name_fr
```

I have a validation for uniqueness. 

```ruby
# /app/models/category.rb
...
translates :name
globalize_accessors
validates :name, presence: true, uniqueness: true
```

How can I get the errors associated to the locale like:

```json
name_en: ["has already been taken"],
name_fr: ["..."]
```

**Comment by voyera** [comment]
Hi there guys, any idea why the field would still show as optional but the field has a "needs to be filled" overlay so it seem to pick up the validation.

  # Internalization of fields
  translates :title, :tagline, :description, :itineary
  globalize_accessors locales: [:en, :fr],
                      attributes: [:title, :tagline, :description, :itineary]
  accepts_nested_attributes_for :translations, allow_destroy: true

  # Validation
  validates_associated :translations
  translation_class.validates :title, presence: true

**Comment by artem-fans** [comment]
Thanks @scarfacedeb, just what I was looking for!
