### ISSUE TITLE
Eager loading fails on STI

### ISSUE THREAD

**Issue by sbuhr** [globalize/globalize#391]
Is there any way to eager load the translations? I always end up in n+1 queries.

`Model.includes(:translations)` doesn't work. This occurs in a STI table only.

Any help appreciated.

Edit: STI is supported very well. In my case the AASM gem was outdated.

**Comment by parndt** [comment]
@sbuhr does `Model.joins(:translations)` work? That's what [Refinery CMS is currently using], resulting in a single query.(https://github.com/refinery/refinerycms/blob/master/pages/lib/refinery/pages/finder.rb#L32-L41)

**Comment by sbuhr** [comment]
@parndt No, it doesn't. As mentioned it occurs in STI tables only.

```
Sport.joins(:translations)
  Sport Load (10.8ms)  SELECT `sport_entities`.* FROM `sport_entities` INNER JOIN `sport_entity_translations` ON `sport_entity_translations`.`sport_entity_id` = `sport_entities`.`id` WHERE `sport_entities`.`type` IN ('Sport')
  SportEntity::Translation Load (0.7ms)  SELECT `sport_entity_translations`.* FROM `sport_entity_translations`  WHERE `sport_entity_translations`.`sport_entity_id` = 1519
  SportEntity::Translation Load (0.7ms)  SELECT `sport_entity_translations`.* FROM `sport_entity_translations`  WHERE `sport_entity_translations`.`sport_entity_id` = 1519
  SportEntity::Translation Load (0.6ms)  SELECT `sport_entity_translations`.* FROM `sport_entity_translations`  WHERE `sport_entity_translations`.`sport_entity_id` = 1519
  SportEntity::Translation Load (0.7ms)  SELECT `sport_entity_translations`.* FROM `sport_entity_translations`  WHERE `sport_entity_translations`.`sport_entity_id` = 1520
  SportEntity::Translation Load (0.5ms)  SELECT `sport_entity_translations`.* FROM `sport_entity_translations`  WHERE `sport_entity_translations`.`sport_entity_id` = 1520`
...
```

It loads all 3 translations in single queries.

**Comment by parndt** [comment]
So to clarify, you're saying it eager loads properly with STI tables or it fails to eager load *only* on STI?

**Comment by sbuhr** [comment]
It fails to eager load only on STI.


> Am 05.01.2015 um 22:25 schrieb Philip Arndt <notifications@github.com>:
> 
> it fails to eager load only on STI?
>

**Comment by parndt** [comment]
Sorry, I see now that you wrote that in your initial problem description. I've updated the title of the issue so that I don't ask again later :smile:

**Comment by dcarneiro** [comment]
@sbuhr, I resolver that problem with `Model.with_translations`. It still does 1+1 queries, but it's a lot better than n+1.

**Comment by scarfacedeb** [comment]
@dcarneiro Could you provide the internals of `Sport` and `SportEntity`?

I can't reproduce your issue with my setup:
```ruby
class Computer < ActiveRecord::Base
   translates :desc, :url
end

class Mac < Computer
end

class PC < Computer
end
```

```
[15] pry(main)> Mac.includes(:translations)
  Mac Load (0.2ms)  SELECT "computers".* FROM "computers" WHERE "computers"."type" IN ('Mac')
  Computer::Translation Load (0.3ms)  SELECT "computer_translations".* FROM "computer_translations" WHERE "computer_translations"."computer_id" IN (2, 3)
```

The only known issue is that if you try to call `where` with translated attributes, it would produce `LEFT OUTER JOIN` old-style query:
```
[24] pry(main)> Mac.where(desc: 'ENG DESC').includes(:translations)
  SQL (0.2ms)  SELECT "computers"."id" AS t0_r0, "computers"."name" AS t0_r1, "computers"."browser" AS t0_r2, "computers"."type" AS t0_r3, "computers"."created_at" AS t0_r4, "computers"."updated_at" AS t0_r5, "computer_translations"."id" AS t1_r0, "computer_translations"."computer_id" AS t1_r1, "computer_translations"."locale" AS t1_r2, "computer_translations"."created_at" AS t1_r3, "computer_translations"."updated_at" AS t1_r4, "computer_translations"."desc" AS t1_r5, "computer_translations"."url" AS t1_r6 FROM "computers" INNER JOIN "computer_translations" ON "computer_translations"."computer_id" = "computers"."id" WHERE "computers"."type" IN ('Mac') AND "computer_translations"."desc" = 'ENG DESC' AND "computer_translations"."locale" = ?  [["locale", "en"]]
```

In that case it's better to use `preload`, instead of `includes` and in fact `with_translations` uses `preload` under the hood.

**Comment by sbuhr** [comment]
sport_entity.rb

```
class SportEntity < ActiveRecord::Base
  resourcify
  has_paper_trail :ignore => [:updated_at,:sort]
  acts_as_nested_set :order_column => :sort
  validates_presence_of(:name)
  alias_attribute :state, :aasm_state
  has_and_belongs_to_many :tip_types

 has_one :limit_set

  translates :name
  
  include AASM
  
  aasm do
    state :pending, initial: true
    state :active
    state :stopped

    event :activate do
      transitions from: [:pending, :stopped], to: :active
    end

    event :stop do
      transitions from: [:pending, :active], to: :stopped
    end
  end
end
```

sport.rb

```
class Sport < SportEntity
  validates_uniqueness_of :super_id, :allow_nil => true
  has_many :matches, :primary_key => :super_id
  scope :oddscreator, -> { where(valid_for_oddscreator: true) }
end
```

**Comment by scarfacedeb** [comment]
@sbuhr I added paper_trail, awesome_nested_set and similar validations to my models, but it didn't help.

To clarify: you're getting N+1 queries when you're just running `Sport.includes(:translations)`, correct?

Could you remove any other macros from the models and try to run the same query only with `translates :name` in the `SportEntity`?
It could help to pinpoint the source of this issue.

**Comment by sbuhr** [comment]
Hi,

i will. But it'll take until tomorrow.

Thanks for your effort!

**Comment by sbuhr** [comment]
Ok, AASM is guilty :D Once I put it back in the eager loading is broken.
```Sport.method(:includes).source_location``` returns ```["/Users/sonkebuhr/.rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0/lib/active_record/querying.rb", 10]```

**Comment by scarfacedeb** [comment]
https://github.com/aasm/aasm/pull/209 could be related to your problem.
Have you tried aasm from master?

**Comment by sbuhr** [comment]
@scarfacedeb Thanks! Problem solved!

**Comment by simi** [comment]
:confetti_ball:
