### ISSUE TITLE
Can't Order Translated Country Names

### ISSUE THREAD

**Issue by msdundar** [globalize/globalize#394]
I'm using globalize gem to translate country names in my application. I'm trying to order countries by their names but it's not working. Here are model and view.

**country.rb model =>**

```ruby
class Country < ActiveRecord::Base
  translates :name

  scope :ordered, -> { order("country_translations.name ASC") }

  def self.translated_country_list
    includes(:translations).with_locales([:en, :tr]).ordered
  end
end
```

**In view =>**

```ruby
<%= f.input :country_id, :collection => Country.translated_country_list, :required => true, :autofocus => true, label: false, hint: "* #{t("general.choose_nationality")}" %>
```

**Comment by msdundar** [comment]
Seems like ordering is not working with fallbacks. Otherwise:

```ruby
def self.translated_country_list
    includes(:translations).with_locales(I18n.locale).ordered
end
```

is working.

**Comment by simi** [comment]
What do you mean by `not working`? Is there any error raised? Can you show some logs?

**Comment by msdundar** [comment]
@simi Simply, it is not ordering them by their names. There is no error.

Same problem: http://stackoverflow.com/questions/3596603/how-to-order-a-query-by-a-translated-field-using-globalize

One more: http://stackoverflow.com/questions/16041392/globalize3-order-records-by-translated-attributes-and-taking-fallbacks-into-cons

**Comment by simi** [comment]
And is this solved for you? There are some workarounds mentioned in those SO answers.

**Comment by msdundar** [comment]
Yes, using current locale solved issue for now.

**Comment by simi** [comment]
Ahh, I missed https://github.com/globalize/globalize/issues/394#issuecomment-68614955. Thanks for info @msdundar.
