### ISSUE TITLE
Add Fields In Translation Table Without Translate It

### ISSUE THREAD

**Issue by RomainLanz** [globalize/globalize#395]
Hello,

I search on the documentation how to add fields on the translation table without translate it. Like to have `author_id` for `posts`, but I didn't find a correct solution.

Currently, I store the id on text and change the getter with
````ruby
def author
    User.find(self[:author].to_i)
end
````
but it's not a very good code.

Don't we have any possibility to add a relation on the translation table ?

**Comment by leighhalliday** [comment]
Hi Romain. Does the author_id change depending which language/locale you are in? Otherwise I would recommend not translating that field and just using the author_id that you'd have in your posts model. Then you can use normal Rails relations.

```ruby
class Post < ActiveRecord::Base
  translates :title, :body
  belongs_to :author, class_name: 'User'
end
```

**Comment by RomainLanz** [comment]
It's not write on the documentation but we can use our Translation class nested with our model.

````ruby
class Post < ActiveRecord::Base

  translates :title, :content, :versioning => :paper_trail

  class Translation < Globalize::ActiveRecord::Translation
    belongs_to :author, class_name: 'User'
  end

end
````
