### ISSUE TITLE
NoMethodError: undefined method `page' for #<Globalize::ActiveRecord::QueryMethods::WhereChain:0x007f3ff412c218>

### ISSUE THREAD

**Issue by arsui** [globalize/globalize#399]
when use like Product.page()

it is bug?

**Comment by parndt** [comment]
Can you show us the internals of `Page`?

**Comment by arsui** [comment]
class Product < ActiveRecord::Base
  include ProductSearch
  extend FriendlyId
  translates :title
  
  has_many :titles    , dependent: :destroy, as: :locale_titleable
  has_many :prices    , dependent: :destroy, extend: Price::Extension
  has_many :inventory   , class_name: 'Inventory'

  friendly_id :slug

  validates :slug , :weight, presence: true
  validates :slug , length: { maximum: 64  }, allow_blank: true

  accepts_nested_attributes_for :prices

....
end

**Comment by parndt** [comment]
@arsui have you forgotten to apply whatever pagination library, or is that injected straight onto ActiveRecord::Base?
