### ISSUE TITLE
Globalize 4.0.3 does not store default language translation in translation table

### ISSUE THREAD

**Issue by hucky8** [globalize/globalize#400]
My default language is :de, 
when I pass following string to update a translation ( the title attribute should get translated )

``` ruby
"question_attributes"=>{
  "title"=>"Frage",
  "id"=>515,
  "createdby"=>2,
  "translations_attributes"=>[
    {
      "id"=>1296,
      "locale"=>"fr",
      "title"=>"Questionfr",
    },
    {
      "id"=>1295,
      "locale"=>"en",
      "title"=>"Questionen",
    },
    {
      "id"=>1294,
      "locale"=>"de",
      "title"=>"FrageDE",
    }
  ]
}
```

There is a translation for :de in the table, but it does not get updated from "Frage" to "FrageDE"
When I update the title attribute from the main table it works, the :de translation gets updated

``` ruby
"question_attributes"=>{
  "title"=>"Frage"
 }
```

**Comment by parndt** [comment]
Do the other translations get saved properly?

**Comment by hucky8** [comment]
Yes, the other translations get updated properly

**Comment by parndt** [comment]
I'm surprised why, if DE is the default, updating the title in the main part of the hash isn't saving it? Are you expecting the sub hash to override the main hash?

**Comment by hucky8** [comment]
I was surprised as well, so far the main part was overridden by the subhash (only for the default lang) now its the opposide.

Yes I was expecting that the subhash overrides the main part,I wrote all my translations mechanisms like that, it was easier.

**Comment by parndt** [comment]
Can you please try globalize versions `4.0.0`, `4.0.1`, and `4.0.2`?

**Comment by hucky8** [comment]
I tried all this versions, with 4.0.0 and 4.0.1 i ran into this issue:  #357 
it was no update possible, 4.0.2 did not work as expected
I found out, that records in the translation table doesn't get deleted, when I delete a record in the main table, my Model:

```ruby
    class Question < ActiveRecord::Base
      #relations omited

      translates :description, :hint, :title, :fallbacks_for_empty_translations => true
      globalize_accessors

      store_accessor :question_properties, :stars, :comment

      serialize :solution, JSON

      accepts_nested_attributes_for :fields, allow_destroy: true, update_only: true
      accepts_nested_attributes_for :translations

    end

**Comment by domicode** [comment]
Is there any update on this? Or any fix for it? I encounter the same problem.

**Comment by parndt** [comment]
Can you try version 5.1.0?
