### ISSUE TITLE
update_attributes successfully saves, even with invalid attributes

### ISSUE THREAD

**Issue by tekin** [globalize/globalize#401]
Calling `update_attributes` with invalid attributes succeeds when an explicit locale is passed in.
Here's a failing test: https://github.com/tekin/globalize/commit/c67d2875e647f747fb0aaf0f895a53a816ba38f6

**Comment by parndt** [comment]
Whoa, thanks for reporting!

**Comment by tekin** [comment]
I'm trying to dig into this some more but I'm having trouble understanding some of the code. Specifically, what is the intention of having a `locale` attribute on the translated model's table? The `words` table in the test suite schema has this and there is also code in the `Globalize::ActiveRecord::InstanceMethods` that interacts with such an attribute, but it's not entirely clear what the usage and expected behaviour is when this attribute is present. Any ideas?

**Comment by parndt** [comment]
The `locale` attribute should only be present on the model's translations table.. so say I had a model called `Page`, I would expect `Page::Translation` to have `locale` but not `Page`, if that makes sense?

**Comment by tekin** [comment]
Yep, that's how I imagined it should work. The problem I'm having is that there appears to be code in `Globalize::ActiveRecord::InstanceMethods` that acts as if there may be a `locale` attribute on the translated model and not just the translsations. For example, [read_attribute](https://github.com/globalize/globalize/blob/master/lib/globalize/active_record/instance_methods.rb#L49) and [with_given_locale](https://github.com/globalize/globalize/blob/master/lib/globalize/active_record/instance_methods.rb#L188).

**Comment by tekin** [comment]
OK, think I've found the "why": https://github.com/globalize/globalize/pull/183. This feature doesn't appear to be mentioned in the readme. I'll see if I can write some words to explain it and get a pull request in...

**Comment by parndt** [comment]
Ah, yeah, and recently we decided that you shouldn't use the column in your original table anymore.. so anything that happens to that column is a side effect.  We should move away from any code that tries to handle this situation in any way.

**Comment by tekin** [comment]
Ok, so rather than updating the readme to give the feature visibility, would a pull request that rips out the behaviour be better?

**Comment by parndt** [comment]
Yes, please!!
