### ISSUE TITLE
How to include translation table in nested scope for order

### ISSUE THREAD

**Issue by phlegx** [globalize/globalize#409]
Hi!

I want to order some records that has a relation to another model (with translations). Here an example:

1) I have a model **Project**
2) I have a model **Task**
3) I have the relation **Project** has_many **Tasks**
4) The model **Task** has attribute **name** globalized (on task_translations table)

Now, I want to order all projects by its tasks name. How can I write this scope?

**Comment by tibra** [comment]
Just had the same problem, solved like:
```
scope :by_name, -> { includes(:translations).order(:name) }
```

**Comment by phlegx** [comment]
No, this don't solves the problem!
I want to start the scope from model **Project** like this:

```ruby
Project.all.joins(:tasks). ...now join the task translations table...

# written in a scope example
class Project < ActiveRecord::Base
    ...
    scope :by_name, -> { joins(:tasks).[JOIN TASK TRANSLATIONS TABLE].order(:name) }
end
```

Your solution starts from model **Task**. If I start the scope from model **Task** I can do:

```ruby
scope :by_name, -> { with_transations(:en).order(:name) }
```

**Comment by phlegx** [comment]
OK, this works:

```ruby
Project.joins(tasks: :translations)

# written in a scope example
class Project < ActiveRecord::Base
    ...
    scope :by_name, -> { joins(tasks: :translations).order('task_translations.name DESC') }
end
```

**Comment by MiladRahmani** [comment]
@phlegx I used that code, but return duplicate records for me, do you know how I can fix that ?
