### ISSUE TITLE
Does globalize create ModelTranslation.rb of translated model?

### ISSUE THREAD

**Issue by phlegx** [globalize/globalize#419]
Hi!

I use some gems and I need to create for every translated model with globalize also a ```{model}_translation.rb``` active record model. Why globalize don't create the translation models by itself? How can I do a dynamic model creation? Here an example why I need this:

```ruby
  belongs_to :place
  has_one :category, through: :place
  has_many :category_translations, through: :category
```

Getting the reflection of association ```has_many :category_translations``` i cannot get the model class ```CategoryTranslation```. If I create the model ```CategoryTranslation```by hand, all works fine.

**Comment by scarfacedeb** [comment]
@phlegx you can get Translation model via `Model.translation_class`

**Comment by phlegx** [comment]
@scarfacedeb and when I do the following:

```ruby
User.all.joins(:category_translations).where(...)
```

I get a reflection error ```from /home/user/.rvm/gems/ruby-2.1.4/gems/activerecord-4.1.7/lib/active_record/reflection.rb:100:in `_reflect_on_association'```.

**Comment by phlegx** [comment]
With the comment of @scarfacedeb I have found the solutions in the gems. Joins are made with:

```ruby
User.all.joins(category: :translations)
```

```Model.translation_class``` helps a lot to do a join dynamically. Thx!
