### ISSUE TITLE
undefined method 'delete' on reloading translated model instance

### ISSUE THREAD

**Issue by hotsen** [globalize/globalize#426]
Having a translated model with Globalize 4.0.3, Rails 4.2. and Ruby 2.1.1, calling @model.reload raises the following exception ...

NoMethodError: undefined method `delete' for #<ActiveRecord::AttributeSet:0x00000101cc8678>
	from /.../.rvm/gems/ruby-2.1.1@game/gems/globalize-4.0.3/lib/globalize/active_record/instance_methods.rb:96:in `block in reload'
	from /.../.rvm/gems/ruby-2.1.1@game/gems/globalize-4.0.3/lib/globalize/active_record/instance_methods.rb:96:in `each'
	from /.../.rvm/gems/ruby-2.1.1@game/gems/globalize-4.0.3/lib/globalize/active_record/instance_methods.rb:96:in `reload'
	from (irb):2

**Comment by qntn** [comment]
Hi @hotsen,

Did you find a way to solve your issue ?

I got the same one.

Could you help me ?

Thank you.

**Comment by qntn** [comment]
OK my bad.

I found the issue. I recently updated activerecord to 4.2 and as it is mentioned in the readme, I should use the version 5.1.0 of globalize.

It works now.

Bye.
