### ISSUE TITLE
Pluck?

### ISSUE THREAD

**Issue by folivi** [globalize/globalize#427]
Hi,
how can I use pluck?
eg. Model.pluck(:name, :id) 
with name  transalated
For now pluck only returns ids
and Sport::Translation.group(:id).pluck(:name, :id) returns results for every locale

Cheers

**Comment by parndt** [comment]
Just like that, but joining to the translations table:

```ruby
Model.joins(:translations).pluck(:name, :id)
```

**Comment by folivi** [comment]
thanks for the answer but it doesn't work
`Sport.joins(:translations).pluck(:name, :id)`
returns [[nil, 2], [nil, 2], [nil, 1], [nil, 1], [nil, 3], [nil, 3], [nil, 4], [nil, 4]] 
`Sport.joins(:translations).group("sports.id").pluck(:name, :id)`
=> [[nil, 2], [nil, 1], [nil, 3], [nil, 4]]

**Comment by shioyama** [comment]
Tested on globalize 5.1.0:

```ruby
[1] pry> p = Post.create(title: "a title")=> #<Post:0x00000003ec6de8 id: 1, blog_id: nil, published: nil>
[2] pry> Post.joins(:translations).pluck(:title)
=> ["a title"]
```

**Comment by folivi** [comment]
Hi @shioyama , sorry to bother but it's doesn't work at all
Is it a new feature? as the latest known version of globalize is 5.0.1 (nothing to update when you try gem update)
I'm on rails 4.2 and postgresql

**Comment by scarfacedeb** [comment]
@folivi it works with 5.0.1 for me too.
```ruby
[18] pry(main)> Page.joins(:translations).where('page_translations.locale = ?', Globalize.locale).group("pages.id").pluck(:title, :id)
   (0.2ms)  SELECT title, "pages"."id" FROM "pages" INNER JOIN "page_translations" ON "page_translations"."page_id" = "pages"."id" WHERE (page_translations.locale = 'en') GROUP BY pages.id
=> [["Title eng", 1], ["ENG", 2]]
[19] pry(main)> Globalize::Version
=> "5.0.1"
```

Btw, you have to add something similar to `.where('page_translations.locale = ?', Globalize.locale)` to your query, because it would just get the first translation without it.

Could you provide your Sport model source code?

**Comment by folivi** [comment]
@scarfacedeb here is the class
class Sport < ActiveRecord::Base
  translates :name, :description, :slug
  include FriendlyId
  friendly_id :name, use: [:slugged, :finders]
end

from the console:
> `Sport.joins(:translations).where('sport_translations.locale =?', Globalize.locale)`
=> ` #<ActiveRecord::Relation [#<Sport id: 1, name: "Football", label: "Football", description: "22 guys running after a ball", active: true, created_at: "2015-02-24 23:13:35", updated_at: "2015-02-24 23:52:48", slug: "football", picture: "football.jpg">, #<Sport id: 3, name: "Tennis", label: "Tennis", description: "Tennis", active: true, created_at: "2015-02-25 17:35:00", updated_at: "2015-02-25 17:36:14", slug: "tennis", picture: nil>, #<Sport id: 4, name: "Running", label: "Running", description: "Running", active: true, created_at: "2015-02-25 17:37:35", updated_at: "2015-02-25 17:38:00", slug: "running", picture: nil>, #<Sport id: 2, name: "Basketball", label: "Basketball", description: "nba", active: true, created_at: "2015-02-24 23:22:28", updated_at: "2015-03-04 15:42:08", slug: "basketball", picture: "Basketball.png">]> `

> ` Sport.joins(:translations).where('sport_translations.locale =?', Globalize.locale).pluck(:name)`
=> ` [nil, nil, nil, nil] `

**Comment by parndt** [comment]
The `name` column shouldn't still be on the `Sport` model, it should be fully moved to `Sport`'s translations table.  Were these records created before adding globalize?

**Comment by folivi** [comment]
@parndt Yes they were.

**Comment by parndt** [comment]
Okay, so chances are they're just not translated yet.  Can you show us the output of this:

```ruby
Sport.translation_class.all
```

**Comment by folivi** [comment]
They are translated.
Here command result
`
 Sport.translation_class.all
  Sport::Translation Load (1.9ms)  SELECT "sport_translations".* FROM "sport_translations"
 => #<ActiveRecord::Relation [#<Sport::Translation id: 1, sport_id: 1, locale: "en", created_at: "2015-02-24 23:13:35", updated_at: "2015-02-24 23:20:41", name: "Football", description: "22 guys running after a ball", slug: "football">, #<Sport::Translation id: 2, sport_id: 1, locale: "fr", created_at: "2015-02-24 23:14:19", updated_at: "2015-02-24 23:21:42", name: "Football", description: "22 mecs qui courrent derrière une baballe", slug: "football">, #<Sport::Translation id: 3, sport_id: 2, locale: "fr", created_at: "2015-02-24 23:22:28", updated_at: "2015-02-24 23:22:28", name: "Basketball", description: "De grands blacks qui se passent une baballe", slug: "basketball">, #<Sport::Translation id: 5, sport_id: 3, locale: "en", created_at: "2015-02-25 17:35:00", updated_at: "2015-02-25 17:35:00", name: "Tennis", description: "Tennis", slug: "tennis">, #<Sport::Translation id: 6, sport_id: 3, locale: "fr", created_at: "2015-02-25 17:36:14", updated_at: "2015-02-25 17:36:14", name: "Tennis", description: "22 guys running after a ball", slug: "tennis">, #<Sport::Translation id: 7, sport_id: 4, locale: "fr", created_at: "2015-02-25 17:37:35", updated_at: "2015-02-25 17:37:35", name: "Course à pied", description: "Course à pied", slug: "course-a-pied">, #<Sport::Translation id: 8, sport_id: 4, locale: "en", created_at: "2015-02-25 17:38:00", updated_at: "2015-02-25 17:38:00", name: "Running", description: "Running", slug: "running">, #<Sport::Translation id: 4, sport_id: 2, locale: "en", created_at: "2015-02-24 23:23:03", updated_at: "2015-03-04 15:42:08", name: "Basketball", description: "nba", slug: "basketball">]> 
2.1.3 :002 > `

**Comment by parndt** [comment]
Can you say what `Sport.joins(:translations).where('sport_translations.locale =?', Globalize.locale).to_sql` produces? 

And also what happens if you just do this: `Sport.joins(:translations).where('sport_translations.locale =?', Globalize.locale).map(&:name)`

**Comment by folivi** [comment]
the first command outputs this
`=> "SELECT \"sports\".* FROM \"sports\" INNER JOIN \"sport_translations\" ON \"sport_translations\".\"sport_id\" = \"sports\".\"id\" WHERE (sport_translations.locale ='en')" `
the second:
` => ["Football", "Tennis", "Course à pied", "Basketball"] `

**Comment by parndt** [comment]
Weird, so just pluck isn't working, and only for you.  I'm stumped.

**Comment by folivi** [comment]
I'll start a new project from scratch with the 5.0.1 and let you know if it's still happening.
thank you for your time

**Comment by shioyama** [comment]
@folivi do you have any other gems that might be conflicting with globalize? Or are you doing anything else special with models in your application?

**Comment by folivi** [comment]
Only possible cause would have been TranslationIO but apparently it's not conflicting

here is my gemfile

source 'https://rubygems.org'

ruby '2.1.3'
gem 'rails', '4.2.0'
gem 'pg'
gem 'less-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'carrierwave'#, '~> 0.10.0'
gem 'carrierwave-serializable'

gem 'capistrano-rails', group: :development

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'factory_girl_rails'
  gem 'rspec-rails', '~> 3.0.0.beta2'
  gem 'letter_opener'
  gem 'annotate'

end
gem 'globalize' #, '5.1.0'
gem 'slim-rails'
gem 'angular-rails-templates'
gem "bower-rails", "~> 0.9.2"
gem 'pg_search', '~> 0.7.6'
gem 'select2-rails', '~> 3.5.9.1'
gem 'devise', '~> 3.4.0'
gem 'devise-i18n', '~> 0.11.2'
gem 'pundit', '~> 0.3.0'
gem 'omniauth'
gem 'koala'
gem 'omniauth-facebook'
gem 'acts_as_votable', github: 'ryanto/acts_as_votable', branch: 'bf6104266406967f99667da407b8f21f1a28831b'
gem 'friendly_id', '~> 5.0.4'
gem 'whenever', '~> 0.9.3', require: false
#gem 'translation'
gem 'puma'

**Comment by shioyama** [comment]
Yep those don't look like they would have much impact on this... no idea.

**Comment by scarfacedeb** [comment]
@folivi I think I may know what's going on.
You have `name` columns in `sports` and `sport_translations` tables.
And `pluck(:name)` probably produces something like `SELECT sports.name, sports.id FROM sports`, because you have name column in sports.

But when you don't have that column in the translated table, it would produce `SELECT name, sports.id FROM sport INNER JOIN sport_translations...`.
And due to joining, you'll get `sport_translations.name` columns in the output.

So, to solve your problem, you can use `pluck("sport_translations.name")` instead of `pluck(:name)`.

But I would advise to remove name column from sports table completely.

**Comment by scarfacedeb** [comment]
Moreover, I was able to reproduce your issue when I also added title column to translated and translation tables.

**Comment by parndt** [comment]
Ah - that's not supported. Removing the column from the original table is the official recommendation of globalize now.

**Comment by padde** [comment]
@parndt would it be feasible to extend `pluck` so that it automatically joins the translations table when a translated attribute is referenced, and scope it to the appropriate table name? Similar to https://github.com/globalize/globalize/pull/447

**Comment by parndt** [comment]
@padde feasible, sure, if you were to write the patch and lots of tests for it so that we don't break other use cases and to make sure this one would keep working.

**Comment by simi** [comment]
I think it is possible to reuse original [pluck tests](https://github.com/rails/rails/blob/7d14bd3ff553d6aba11a50b43773bc21ae20f31e/activerecord/test/cases/calculations_test.rb#L493-L654).
