### ISSUE TITLE
Translations should :touch globalized_model

### ISSUE THREAD

**Issue by batamire** [globalize/globalize#432]
Commit [c96a11d](https://github.com/globalize/globalize/commit/c96a11d19b406761eaa77c5fdd50d5fdbb0c2efb) broke this...
Cache key changes but callbacks don't get fired on globalized_model without :touch.
I think modifying translations should touch globalized_model.

**Comment by shioyama** [comment]
See comments on #330, e.g. [this one](https://github.com/globalize/globalize/pull/330#issuecomment-50129369):

> I'm seeing a problem due to this patch and using optimistic locking. When you try to delete an object that uses the 'translates' call, like my Post class, you will get an ActiveRecord::StaleObject error. It's because the 'touch' is causing the object to be updated because of the touch, but the in memory lock_version isn't updated.
