### ISSUE TITLE
Active model 4.1.1 error when destroy record (Globalize 4.0.3)

### ISSUE THREAD

**Issue by OpakAlex** [globalize/globalize#434]
When i Destroy record, i have this error:
NoMethodError: undefined method `name' for nil:NilClass

```
class Spa < ActiveModel::Base
  translates :name, :description, :address
  validates_presence_of :city, :country, :spa_type, :name
end
```

Spa.frist.destroy => NoMethodError: undefined method `name' for nil:NilClass

What is wrong?

**Comment by OpakAlex** [comment]
Problem in: reflection => nil.

```
        def cached_counter_attribute_name(reflection = reflection)
          options[:counter_cache] || "#{reflection.name}_count"
        end
```

**Comment by jon3dc** [comment]
Hi did you resolve this issue - I am experiencing the same
