### ISSUE TITLE
Ordering with current locale and fallback

### ISSUE THREAD

**Issue by acaron** [globalize/globalize#439]
I tried many ways to order with the current locale and the fallback but nothing worked. For example, I have `fr` as the current locale and `en` as the fallback locale. You have to create an item in english then you create or not the french version. It must order by the french version if it exist or by the english version. Actually, you can do: `animals.with_translations(I18n.locale).order('LOWER(name) ASC')` but, if some french translations is missing, it only display the one that exists and not the english one. Here is an example of the result I want to have:
```
Bird (locale: en)
Cat (locale: en)
Chien (locale: fr)
Hibou (locale: fr)
Ours (locale: fr)
Owl (locale: en)
Singe (locale: fr)
```

I can do it with this query (not the real names) if I want the french language and english as fallback:
```
SELECT * FROM animals
LEFT OUTER JOIN animal_translations ON animal_translations.animal_id = animals.id
AND animal_translations.locale = (
    SELECT t.locale
    FROM animal_translations AS t
    WHERE t.animals_id = animal_translations.animals_id
    ORDER BY CASE t.locale WHEN 'fr' THEN 0 WHEN 'en' THEN 1 ELSE 2 END, t.locale ASC
    LIMIT 1
) ORDER BY "title" ASC
```

So this part is responsible to order and pick the first one (I tried with `ORDER BY ('fr', 'en')...` it doesn't work):
```
ORDER BY CASE t.locale WHEN 'fr' THEN 0 WHEN 'en' THEN 1 ELSE 2 END, t.locale ASC LIMIT 1
```

It gives a weight to every line and you pick the lowest one. I put that in a scope but it would be nice to have a function in Globalize that do this.

Can someone help me if it already exists? Or, else, I suggest to do something like that (or a better way) to achieve this. I'm using PostgreSQL

**Comment by jaemo** [comment]
I'm having the exact same issue. In my controller I have

**Comment by jaemo** [comment]
I have the same issue. 

```@cities = City.with_translations(I18n.locale).order(name: :asc).page(params[:page]).per(10)```

returns all 41 cities in english, and 2 in french. 

I in config/application.rb I have 
``` 
    I18n.available_locales = [:en, :fr]
    config.i18n.fallbacks = {'fr' => 'en'}
```

I'm using Postgres, Rails 4.2.0, Gloabilize 5.0.0, Globalize Accessors and Globalize Versioning. 



Logs for when I am using :fr are as follows: 
```
Started GET "/admin/cities?admin_locale=fr" for 127.0.0.1 at 2015-04-30 00:55:03 -0600
Processing by Admin::CitiesController#index as HTML
  Parameters: {"admin_locale"=>"fr"}
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
  City Load (0.3ms)  SELECT  "cities".* FROM "cities" INNER JOIN "city_translations" ON "city_translations"."city_id" = "cities"."id" WHERE "city_translations"."locale" = $1  ORDER BY "city_translations"."name" ASC LIMIT 10 OFFSET 0  [["locale", "fr"]]
  City::Translation Load (0.3ms)  SELECT "city_translations".* FROM "city_translations" WHERE "city_translations"."city_id" IN (10, 1)
   (0.1ms)  SELECT COUNT(*) FROM "locations" WHERE "locations"."city_id" = $1  [["city_id", 10]]
   (0.2ms)  SELECT COUNT(*) FROM "locations" WHERE "locations"."city_id" = $1  [["city_id", 1]]
 ```

In :en it looks like this:
``` 
Started GET "/admin/cities?admin_locale=en" for 127.0.0.1 at 2015-04-30 00:56:08 -0600
Processing by Admin::CitiesController#index as HTML
  Parameters: {"admin_locale"=>"en"}
  User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
  City Load (0.3ms)  SELECT  "cities".* FROM "cities" INNER JOIN "city_translations" ON "city_translations"."city_id" = "cities"."id" WHERE "city_translations"."locale" = $1  ORDER BY "city_translations"."name" ASC LIMIT 10 OFFSET 0  [["locale", "en"]]
  City::Translation Load (0.2ms)  SELECT "city_translations".* FROM "city_translations" WHERE "city_translations"."city_id" IN (10, 2, 29, 3, 22, 30, 23, 11, 1, 8)
   (0.2ms)  SELECT COUNT(*) FROM "locations" WHERE "locations"."city_id" = $1  [["city_id", 10]]
   (0.1ms)  SELECT COUNT(*) FROM "locations" WHERE "locations"."city_id" = $1  [["city_id", 2]]
   (0.1ms)  SELECT COUNT(*) FROM "locations" WHERE "locations"."city_id" = $1  [["city_id", 29]]
   (0.1ms)  SELECT COUNT(*) FROM "locations" WHERE "locations"."city_id" = $1  [["city_id", 3]]
   (0.1ms)  SELECT COUNT(*) FROM "locations" WHERE "locations"."city_id" = $1  [["city_id", 22]]
   (0.2ms)  SELECT COUNT(*) FROM "locations" WHERE "locations"."city_id" = $1  [["city_id", 30]]
   (0.1ms)  SELECT COUNT(*) FROM "locations" WHERE "locations"."city_id" = $1  [["city_id", 23]]
   (0.1ms)  SELECT COUNT(*) FROM "locations" WHERE "locations"."city_id" = $1  [["city_id", 11]]
   (0.1ms)  SELECT COUNT(*) FROM "locations" WHERE "locations"."city_id" = $1  [["city_id", 1]]
   (0.2ms)  SELECT COUNT(*) FROM "locations" WHERE "locations"."city_id" = $1  [["city_id", 8]]
```

Not sure if pagination is the problem, though it's worth noting if I remove `.page(params[:page]).per(10)` the behaviour is identical. 

Very confusing...

**Comment by acaron** [comment]
Yes, it seems to eager load in english. When a translation is missing, it calls the french fallback so your behavior seems normal. My specific problem is when I need to order by the current language and the fallback...

**Comment by jaemo** [comment]
Unless I am misunderstanding how fallbacks work, I think you may be mistaken. 
I have 41 English records. 2 in French. 

When the French is missing, the behaviour should be to fallback to the English (as per my config). This is not what is occurring, I am instead seeing 2 records in French and no English fallbacks. 

I should see the same number of records in either case, with 2 of them showing up in French (when locale is set to :fr), and the rest in English.

**Comment by acaron** [comment]
Ahh I understand now ! Of course, I have this behavior when I'm using: MyModel.with_translations(I18n.locale)

**Comment by santostiago** [comment]
Any fix for this yet?
