### ISSUE TITLE
No option on write_attribute to return original method?

### ISSUE THREAD

**Issue by FireWhale** [globalize/globalize#440]
I was digging through the instance methods and noticed that the read_attribute method has an option to return the original method by passing in :translated => false. 

lib/globalize/active_record/instance_methods.rb
```ruby
def read_attribute(name, options = {})
    options = {:translated => true, :locale => nil}.merge(options)
    return super(name) unless options[:translated]

    ...
end
```

However, there is no such option for write_attribute. 

I do understand that most applications drop the original column when they implement globalize, so they never run into this problem, but I don't see a reason why it would be a bad idea either. 

Is there a reason for this that I'm missing? Otherwise, I'd be happy to submit a pull request to add that functionality in if it's justified.

**Comment by parndt** [comment]
I have no objection, provided that it's fully tested.

**Comment by FireWhale** [comment]
I looked into this today and it was not as simple as I thought.

While changing the write_attribute method was easy enough, saving an untranslated attribute was another matter. Globalize's methods interfered with ActiveRecord's validation and saving of the untranslated attribute during a save/update call. 

I believe one would have to touch a lot of globalize's methods to get it working correctly. There's nothing wrong with globalize's implementation, but I think it would need a fair bit of code to handle both translated and untranslated attributes of the same name side-by-side. 

Unfortunately, I don't have the time to work on something of that scope. Good luck to anyone that tries in the future, though.
