### ISSUE TITLE
find new records broken?

### ISSUE THREAD

**Issue by guyisra** [globalize/globalize#445]
Migrating translation from existing records work fine. If I create a new record I can find it by its id, but I can't do things like

`User.where("name ILIKE :q", q: "%#{query}%")`

since it returns an empty relation

I am using 

```
translates :name, :fallbacks_for_empty_translations => true
globalize_accessors :locales => I18n.available_locales, :attributes => [:name]
```

are there known issues with new records? or should I do anything specific after the record is created?

using Rails 4.2 and Postgresql 9.3

**Comment by tagliala** [comment]
Same here. 

This issue apparently started with globalize 5.x, 4.x with Rails 4.1 worked just fine

I've also tried `fallbacks_for_empty_translations: true`, but the model fields are still empty.

```rb
2.2.3 :016 > Gem.loaded_specs['globalize'].version
 => #<Gem::Version "4.0.3"> 
2.2.3 :017 > Post.create(title: 'My Title', text: 'Lorem Ipsum')
   (0.1ms)  begin transaction
  SQL (0.3ms)  INSERT INTO "posts" ("text", "title") VALUES (?, ?)  [["text", "Lorem Ipsum"], ["title", "My Title"]]
  SQL (0.2ms)  INSERT INTO "post_translations" ("created_at", "locale", "post_id", "text", "title", "updated_at") VALUES (?, ?, ?, ?, ?, ?)  [["created_at", "2015-11-15 17:55:16.060182"], ["locale", "en"], ["post_id", 5], ["text", "Lorem Ipsum"], ["title", "My Title"], ["updated_at", "2015-11-15 17:55:16.060182"]]
  Post Load (0.0ms)  SELECT  "posts".* FROM "posts"  WHERE "posts"."id" = ? LIMIT 1  [["id", 5]]
   (1.5ms)  commit transaction
 => #<Post id: 5, title: "My Title", text: "Lorem Ipsum"> 
2.2.3 :018 > 
```

```rb
2.2.3 :004 > Gem.loaded_specs['globalize'].version
 => #<Gem::Version "5.0.1"> 
2.2.3 :005 > Post.create(title: 'My Title', text: 'Lorem Ipsum')
   (0.1ms)  begin transaction
  SQL (0.4ms)  INSERT INTO "posts" DEFAULT VALUES
  SQL (0.1ms)  INSERT INTO "post_translations" ("locale", "title", "text", "post_id", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?, ?)  [["locale", "en"], ["title", "My Title"], ["text", "Lorem Ipsum"], ["post_id", 7], ["created_at", "2015-11-15 17:54:50.719737"], ["updated_at", "2015-11-15 17:54:50.719737"]]
   (1.7ms)  commit transaction
 => #<Post id: 7, title: "My Title", text: "Lorem Ipsum"> 
2.2.3 :006 > 
```

**Comment by tagliala** [comment]
I'm trying to figure it out the problem by myself, but I think I need a while

Any comment from the maintainers?

**Comment by donatoaz** [comment]
+1

Same issue here, doing:

`@product_sets = ProductSet.order(:name).where("name ilike ?", "%#{params[:term]}%")`

results in

> SELECT "product_sets".* FROM "product_sets" WHERE (name ilike '%Panorama%')  ORDER BY product_set_translations.name
> Completed 500 Internal Server Error in 250ms (ActiveRecord: 24.7ms)
> ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "product_set_translations"

**Comment by shioyama** [comment]
From this SQL:

```sql
SQL (0.3ms)  INSERT INTO "posts" ("text", "title") VALUES (?, ?)  [["text", "Lorem Ipsum"], ["title", "My Title"]]
  SQL (0.1ms)  INSERT INTO "post_translations" ("created_at", "locale", "post_id", "text", "title", "updated_at") VALUES (?, ?, ?, ?, ?, ?)  [["created_at", "2015-11-16 13:29:50.088414"], ["locale", "en"], ["post_id", 10], ["text", "Lorem Ipsum"], ["title", "My Title"], ["updated_at", "2015-11-16 13:29:50.088414"]]
  Post Load (0.1ms)  SELECT  "posts".* FROM "posts"  WHERE "posts"."id" = ? LIMIT 1  [["id", 10]]
   (1.7ms)  commit transaction
```

It seems that you have the `text` and `title` columns on both the `posts` table *and* the `post_translations` tables. Is this correct? If so this will break Globalize and generally result in unpredictable things.
