### ISSUE TITLE
Translation table inside other database (for use with stuff like the Apartment gem)

### ISSUE THREAD

**Issue by foeken** [globalize/globalize#455]
I got this working with some minor changes. I opened this issue as reference for other who are trying the same and in hopes of getting a little patch in the gem that fixes a finding Objects on their translated attributes.

First of all, I just use the default stuff to add the database name as a prefix (not really the general idea behind the feature probably, but it works):

```ruby
class Tag < ActiveRecord::Base
  translates :name, table_name: "#{global_database}.tag_translations"
  def self.table_name_prefix
    "#{HealthcareMultiTenant::CareProvider.global_database}."
  end
end
```

Next up, I need to build the translation tables manually, but I think this is a fair trade off.

But then I try the following call:

```ruby
Tag.where(name: "TEST").first
```

I get the exception, which is quite correct:

```
`#{global_database}`.`tag_translations.name` is not a valid column
```

I fixed this with the following change:

```ruby
def parse_translated_conditions(opts)
  if opts.is_a?(Hash) && respond_to?(:translated_attribute_names) && (keys = opts.symbolize_keys.keys & translated_attribute_names).present?
    opts = opts.dup
    keys.each do |key|
      split_name = translated_column_name(key).split(".")
      # If the table name contains a database (more than one dot char)
      if split_name.length > 2
        field = split_name.pop
        opts[split_name.join(".")] = { field => opts.delete(key) || opts.delete(key.to_s) }
      else
        opts[translated_column_name(key)] = opts.delete(key) || opts.delete(key.to_s)
      end
    end
    opts
  end
end
```

The fix could probably be a bit cleaner, but it works ;)

**Comment by alepore** [comment]
@foeken thanks for the code!!
just faced the same problem
