### ISSUE TITLE
Globalize breaks CarrierWave uploader

### ISSUE THREAD

**Issue by partydrone** [globalize/globalize#456]
## Background

Here are the gem versions I'm using:

``` ruby
gem "rails", "4.2.3"
gem "carrierwave" # 0.10.0
gem "globalize" # 5.0.1
```

My model:

``` ruby
class Download < ActiveRecord::Base
  belongs_to :download_type
  has_and_belongs_to_many :products

  translates :title, :part_number, :file

  mount_uploader :file, DownloadFileUploader

  validates :title, presence: true

  def to_param
    "#{id}-#{title.parameterize}"
  end
end
```

And my uploader:

``` ruby
class DownloadFileUploader < CarrierWave::Uploader::Base
  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  def filename
    "#{model.title.parameterize(sep = '_')}-#{I18n.locale}-#{Digest::SHA1.hexdigest file.read}#{File.extname(original_filename)}" if original_filename
  end
end
```
## The Issue

In my view, I want to list a Download and all of the current translations for that download, but it doesn't change the filename for each locale. In the Rails console:

```
> I18n.locale
=> :en

> download = Download.find(481)
=> #<Download id: 481, title: "SmartSensor HD Quick-reference Guide (User)", part_number: "WX-500-0171", download_type_id: 3, created_at: "2015-01-16 22:49:13", updated_at: "2015-04-20 16:59:25", file: "smartsensor_hd_user_quick-reference_guide-20150116...", download_updated_at: nil>

> download.translations.count
=> 8

> download.translated_locales
=> [:de, :en, :es, :fr, :it, :pt, :ru, :"zh-CN"]

> download.file.class
=> DownloadFileUploader

> download.file.url
=> "/uploads/download/file/481/smartsensor_hd_user_quick-reference_guide-20150116154913-en.pdf"

> download.title
=> "SmartSensor HD Quick-reference Guide (User)"

> download.part_number
=> "WX-500-0171"
```

And when the locale changes:

```
> I18n.locale = :de
=> :de

> download
=> #<Download id: 481, title: "SmartSensor HD Kurzanleitung", part_number: "WX-502-0006", download_type_id: 3, created_at: "2015-01-16 22:49:13", updated_at: "2015-04-20 16:59:25", file: "kurzanleitung-20150119113123-de.pdf", download_updated_at: nil>

> download.file.class
=> DownloadFileUploader

> download.file.url
=> "/uploads/download/file/481/smartsensor_hd_user_quick-reference_guide-20150116154913-en.pdf"

> download.title
=> "SmartSensor HD Kurzanleitung"

> download.part_number
=> "WX-502-0006"
```

Notice `download.file.url` doesn't change, even though the `file` attribute of the model has updated. If I try and access the translation directly:

```
> I18n.locale = :de
=> :de

> download.translation.file.class
=> String
```
## Attempted Solution

If I change how the uploader is mounted in my model:

``` ruby
Translation.mount_uploader :file, DownloadFileUploader
```

Existing translations list correctly—including the file, but new uploads break. What gets stored in the database is this:

```
 /uploads/download/translation/file/401/%23%3CActionDispatch%3A%3AHttp%3A%3AUploadedFile%3A0x007f9c12e6fe00%3E
```

And no file is uploaded.

Notice that it inserts `/translation` into the path, which I can fix in the uploader,  the `:id` is wrong (401 instead of 481), and the filename isn't actually a filename—it looks like a URL-escaped string representation of a Ruby object.

If I move `translates :title, :part_number, :file` below `mount_uploader :file, DownloadFileUploader` in my model, Globalize overrides the mounted uploader and that column is returned as class `String` instead of `DownloadFileUploader`.

**Comment by tomash** [comment]
That's funny. CarrierWave's source code is a pretty complicated beast, that'll require some time to investigate. Could you maybe put somewhere on github a minimal Rails app (with upload form and browse views) with this bug in isolation?

**Comment by partydrone** [comment]
I will do that. I may also try something other than CarrierWave (like Paperclip) to see if that will work.

**Comment by parndt** [comment]
As far as I'm aware, CarrierWave is being replaced by [refile](https://github.com/refile/refile)

**Comment by tomash** [comment]
@partydrone regardless of used library, I'm not sure translating url columns (or: using globalize in this way) is a good approach. of course it makes certain things easier (one id for one file, regardless of language), I just don't know if it's a good design.

**Comment by partydrone** [comment]
@parndt, I gave refile a shot, and I really like it. It looks like it works better with globalize than CarrierWave, but now I'm running into new issues (I'll create a new ticket for them).

@tomash, my Download model represents a document or file—a user guide, for example—in general, but we may have _versions_ of that document or file in different languages. So I have a single ID from the `downloads` table to represent the "master" object, but I get specific version information from the associated `download_translations` table based on locale.

I need to group document versions together somehow, whether I use Globalize or not. I can't really think of another design approach that will work, but I'm definitely open to suggestions.

**Comment by forever-sumit** [comment]
Hi Guys,

I'm also facing the the same issue as mentioned by @partydrone .

So want to know do we have any solution for this problem? or we we need to implement our own logic for file field translations.

**Comment by milushov** [comment]
Hey guys @partydrone @forever-sumit what decision did you find end up?

**Comment by richardrails** [comment]
any solution?

**Comment by partydrone** [comment]
No solution to this problem, specifically. I ended up using a different localization gem and upload manager gem altogether. I have since moved on to other projects, and with the new ActiveStorage module in Rails, that would be the next place I would try to make it work.

@milushov @richardrails

**Comment by richardrails** [comment]
I have found solution that works.

**Comment by parndt** [comment]
would you mind sharing the solution you found please @richardrails ?

**Comment by richardrails** [comment]
sure. 

in model:
`Translation.mount_uploader :attachment, PdfTranslationUploader`

in uploader:
```
def store_dir
  "uploads/#{model.class.to_s.underscore}/#{model.locale}/#{mounted_as}/#{model.id}"
end
```

in view (haml):
```
- I18n.available_locales.each do |locale|
  = f.globalize_fields_for locale do |g|
    = g.input :attachment, as: :file
```

lib for `f.globalize_fields_for` form feature:
put it in `lib/plugins/batch_translation_plugin/batch_translation.rb`
```
module ActionView
  module Helpers
    class FormBuilder

      def globalize_fields_for(locale, *args, &proc)
        raise ArgumentError, "Missing block" unless block_given?
        @index = @index.to_i ? @index.to_i + 1 : 1
        object_name = "#{@object_name}[translations_attributes][#{@index}]"
        object = @object.translations.select{|t| t.locale == locale}.first || @object.translations.find_by(locale: locale.to_s)
        @template.concat @template.hidden_field_tag("#{object_name}[id]", object ? object.id : "")
        @template.concat @template.hidden_field_tag("#{object_name}[locale]", locale)
        @template.simple_fields_for(object_name, object, *args, &proc)
      end
    end
  end
end


module Globalize
  module Model
    module ActiveRecord
      module Translated
        module Callbacks
          def enable_nested_attributes
            accepts_nested_attributes_for :translations
          end
        end
        module InstanceMethods
          def after_save
            init_translations if build_all_translations
          end
          # Builds an empty translation for each available
          # locale not in use after creation
          def init_translations
            I18n.available_locales.reject{|key| key == :root }.each do |locale|
              translation = self.translations.find_by(locale: locale.to_s)
              if translation.nil?
                # logger.debug "Building empty translation with locale '#{locale}'"
                translations.build :locale => locale
                save
              end
            end
          end
        end
      end
    end
  end
end
```

require file in `config/initializers/batch_translation.rb`:
```
require 'plugins/batch_translation_plugin/batch_translation'
```

**Comment by parndt** [comment]
Thank you very much! :clap:  I'll close this as there's a workaround posted.
