### ISSUE TITLE
Add options to translation table fields

### ISSUE THREAD

**Issue by dcarneiro** [globalize/globalize#457]
I couldn't find a one liner to add options to a translation table fields. Example: If I have a notifications table which has it's body translated and I want to change to body length to 512 I had to do like this:

```ruby
class CreateNotifications < ActiveRecord::Migration
  def up
    create_table :notifications do |t|
      t.timestamps null: false
    end

    Notification.create_translation_table! body: :string
    change_column :notification_translations, :body, :string, limit: 1000
  end
end
```

Is there a way to pass the limit as an argument to the `create_translation_table method`?

**Comment by tomash** [comment]
I haven't played with migration code of Globalize for a while, but from what I see auxilary options for translation columns (fields) are not pass-able:
https://github.com/globalize/globalize/blob/38270f18ae60c4901cfd388be3449773d2321947/lib/globalize/active_record/migration.rb#L27

That sounds like a great feature to add -- pass columns options or copy over the options from "original" column.
@parndt and @shioyama , what do you think?

**Comment by parndt** [comment]
If we can do it cleanly and well tested, then sure :smile:

**Comment by dcarneiro** [comment]
@tomash @parndt , what's the cleaner syntax for it? We can pass them inside the options:

```ruby
class CreateNotifications < ActiveRecord::Migration
  def up
    create_table :notifications do |t|
    end

    Notification.create_translation_table!({ body: :string }, body: { limit: 1000, default: 'something' })
  end
end
```

but I'm kinda fond of passing the field options in each field:

```ruby
class CreateNotifications < ActiveRecord::Migration
  def up
    create_table :notifications do |t|
    end

    Notification.create_translation_table!({ body: { type: :string, limit: 1000, default: 'something' })
  end
end
```

What do you say?

**Comment by parndt** [comment]
By cleanly I mean the implementation of the feature :smile:

**Comment by dcarneiro** [comment]
ofc :smile: 

but regarding the implementation, do you want me to give it a try using my second approach?

**Comment by parndt** [comment]
Sure, if we can ensure that the API is backward compatible.

**Comment by tomash** [comment]
:+1: for second approach from me, let's keep it clean. @dcarneiro do you need a walk through the code? Most of code that interests you is in the file I linked in previous comment :)

**Comment by dcarneiro** [comment]
@tomash let me look at the code tonight and then I'll poke you if I need some guidance :smile:

**Comment by tomash** [comment]
Feel free. I'd do it myself but it's actually one of the nicest and most readable parts of Globalize codebase (and one that isn't obsoleted by changed in ActiveRecords internal APIs), so it's a perfect occasion to make your first contributions to globalize code :)

**Comment by shioyama** [comment]
@tomash sorry for the late reply, agree sounds reasonable. (The migrations side of the codebase is the part I've touched the least so not much I can contribute off the top of my head.)

**Comment by dcarneiro** [comment]
So, I was digging into the code and I found this file https://github.com/dcarneiro/globalize/blob/master/test/globalize/migration_test.rb:

```ruby
    it 'adds the translations table with options' do
      Migrated.create_translation_table!(:name => {:type => :text, :default => '123'})
      assert_migration_table(:name => :text)
      assert_equal '123', column_default(:name)
    end
```

It looks like globalize already supports this feature :smile:

**Comment by parndt** [comment]
@dcarneiro nice! And with the exact API you wanted.
