### ISSUE TITLE
Globalize.with_locale not saving translation properly.

### ISSUE THREAD

**Issue by snuggs** [globalize/globalize#460]
On a website with support for multiple languages, I have a form where users can enter or edit the translated fields in any locale they select from a drop-down (the selected locale), regardless of the locale they are currently using (the current locale). For example, if I am using the website in English, I can select French from the dropdown, and I can create/edit the French translation.

This is currently working fine for updates, but when creating a new record it always saves the translations to the current locale and never to the selected locale, despite doing both with what is essentially the same code (the only difference is one does @model.save, and the other does @model.update(model_params).

The create method is as follows:

 def create
    @locale = Locale.new(locale_params)

```
if params[:translation][:locale]
  locale_to_update = params[:translation][:locale]
  success_text = 'created with locale: ' + locale_to_update
else
  locale_to_update = I18n.locale
  success_text = 'created'
end

respond_to do |format|
   Globalize.with_locale(locale_to_update) do
      if @locale.save
        format.html { redirect_to admin_locales_url, notice: "Locale was successfully  #{success_text}." }
        format.json { render :show, status: :created, location: @locale }
      else
        format.html { render :new, locals: { target_locale: target_locale(params[:locale][:update]) } }
        format.json { render json: @locale.errors, status: :unprocessable_entity }
      end
   end
end
```

  end
And the update method, which works, and is essentially similar, is:

def update
    if params[:translation][:locale]
      locale_to_update = params[:translation][:locale]
      success_text = 'translated'
    else
      locale_to_update = I18n.locale
      success_text = 'updated'
    end

```
respond_to do |format|
  Globalize.with_locale(locale_to_update) do
    if @locale.update(locale_params)
      format.html { redirect_to admin_locales_url, notice: "Locale was successfully #{success_text}." }
      format.json { render :show, status: :ok, location: [:admin, @locale] }
    else
      format.html {
        if params[:locale][:update].present?
          render :translate, locals: { target_locale: target_locale(params[:locale][:update]) }
        else
          render :edit
        end
      }
      format.json { render json: {errors: @locale.errors.full_messages}, status: :unprocessable_entity }
    end
  end
end
```

  end
In both cases the locale_to_update variable has the correct value (it is the selected locale, not the current locale). The problem is that in the globalize stash, the field values are assigned on the current locale key, and not the selected locale key.

**Comment by shioyama** [comment]
Related to #476 maybe?

**Comment by MGPalmer** [comment]
I'm having the same issue :(

**Comment by giedriusr** [comment]
This is something I'd be interested as well.
