### ISSUE TITLE
Can I write my own [model]_translation.rb model class?

### ISSUE THREAD

**Issue by phlegx** [globalize/globalize#461]
I want to add a reference column in the translation table. How can I add ```belongs_to :reference``` to the model_translation.rb. Can I inherit the model translation class from globalize to my model_translation.rb?

**Comment by tomash** [comment]
Maybe instead of inheritance a cleaner approach would be to use `class_eval`?
See here: https://guides.spreecommerce.com/developer/logic.html

**Comment by phlegx** [comment]
:+1: Thx!
