### ISSUE TITLE
How do I use globalize with factory_girl?

### ISSUE THREAD

**Issue by floydj** [globalize/globalize#463]
I'm sure I must be missing something easy here, but I have the following in my model:

```ruby
class CaseStudy < ActiveRecord::Base
  validates :title, presence: true, uniqueness: true
  validates_presence_of :challenge, :solution, :case_study_category_id
  translates :title, :challenge, :solution, :customer, :location
end
```

And here's my factory:

```ruby
FactoryGirl.define do
  factory :case_study do
    title "Case Study Title"
    challenge 'something'
    solution 'something'
    case_study_category
  end
end
```

Whenever I try to create a factory, I get:

`Validation failed: Title can't be blank`. 

It doesn't matter whether or not I have the title line in the factory. Always says validation failed. Any help would be appreciated.

**Comment by firedev** [comment]
Use `gem globalize_accessors`

**Comment by floydj** [comment]
I still can't figure out how that should work.

In my model:

```ruby
  translates :title, :challenge, :solution, :customer, :location
  globalize_accessors locales: [:en], attributes: [:title]
```

The factory:

```ruby
  factory :case_study do
    title_en "Case Study Title"
    challenge 'something'
    solution 'something'
    case_study_category
  end
```

The spec still fails with `Title can't be blank` when I try to create an instance of the factory.

**Comment by halilim** [comment]
@floydj

1. If your model validates `title` instead of `title_...`,
2. And if you have any other locale than `:en`,
3. And if it's the default one;

then you should add it to the factory:

```ruby
title_en "Case Study Title"
title_etc "Case Study Title In The Other Language"
# ...
```

Because `title_etc` is invoked when `title` is called without specifying a locale, and it would be empty according to your original factory.
