### ISSUE TITLE
N+1 queries ?

### ISSUE THREAD

**Issue by terry90** [globalize/globalize#477]
Bullet is throwing me a "N+1 query" for every model globalized.
```
N+1 Query detected
  Project => [:translations]
  Add to your finder: :includes => [:translations]
```
Is this a compatibility issue ?
Else, I think we should fix this

**Comment by tomash** [comment]
It's by design, you need to explicitly use `includes(:translations)` or `joins(:translations)`. Making one of these included by default (into the default scope) would be asking for trouble.

**Comment by terry90** [comment]
Thank you @tomash !

**Comment by art-solopov** [comment]
Strange but it doesn't seem to work for me. I fire `NewsArticle.includes(:translations)`, and it still produces multiple queries to fetch the translations.

I'm using Rails 5 and pulling globalize from GitHub. Can it be an issue?
