### ISSUE TITLE
Join table error - UnknownAttributeError: unknown attribute 'locale'

### ISSUE THREAD

**Issue by cpilegard** [globalize/globalize#478]
Using ref: '5db91fc'

```
class CommodityVariety < ActiveRecord::Base
  translates :code, :description, fallbacks_for_empty_translations: true
  ...
  has_many :commodity_varieties_regions
  has_many :countries, through: :commodity_varieties_regions
  ...
  accepts_nested_attributes_for :commodity_varieties_regions
end

class Country < ActiveRecord::Base
  translates :short_name, fallbacks_for_empty_translations: true
  ...
  has_many :commodity_varieties_regions
  has_many :commodity_varieties, through: :commodity_varieties_regions
  ...
  default_scope { order(:short_name) }
end

class CommodityVarietiesRegion < ActiveRecord::Base
  belongs_to :commodity_variety
  belongs_to :country
end
```

If I create a `CommodityVariety` with a `country_ids` attribute, I get the following error:

```
ActiveRecord::UnknownAttributeError: unknown attribute 'locale' for CommodityVarietiesRegion
```

I'm not sure why it's looking for a `locale` attribute on the join table. Any ideas?

**Comment by cpilegard** [comment]
It looks like it's related to this issue: https://github.com/globalize/globalize/issues/145. When I remove the default scope on Country, everything works as normal.

**Comment by webzorg** [comment]
This needs a fix. I spent 15 minutes panicking on what went wrong... I was lucky to find this thread online.

**Comment by ismaelga** [comment]
I got the exact same problem but with just a has_many association. with ref 607e6ef
```ruby

class Project < ApplicationRecord
  translates :name, :pitch
  ...
  has_many :income_shares, dependent: :destroy
  ...
end

class IncomeShare < ApplicationRecord
  translates :label
  ...  
  default_scope { order(value: :desc) }
end
```

Changing from `order(value: :desc)` to `order('value desc')` made the error go away.

**NOTE**: While writing this I tried master it works fine with `order(value: :desc)`

**Comment by luukveenis** [comment]
@shioyama I saw that you tried to reproduce this issue in a failing spec. I'm still seeing this issue in my application and have created a minimal Rails app to reproduce it. I included steps to reproduce the issue in the README:
https://github.com/luukveenis/globalize_test

On my `Bar` model I have a `default_scope` that orders by the translated attribute. The issues seems to be that the default scope includes translations in the query and this AR override includes the locale param into the `where_values_hash`:
https://github.com/globalize/globalize/blob/master/lib/patches/active_record/relation.rb

This gets used when building the `has_many :through` record here:
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/has_many_through_association.rb#L85

The reason @ismaelga 's issue went away when using `order('value desc')` is that with a string parameter, `order` won't include translations.

**Comment by phlegx** [comment]
@cpilegard try out this:

```ruby
class CommodityVarietiesRegion < ActiveRecord::Base
  belongs_to :commodity_variety, -> { unscope(where: :locale) }
  belongs_to :country, -> { unscope(where: :locale) }
end
```

Method `unscope` removes what you want from the SQL. I have a similar problem with `has_many :through` and this workaround has solved the problem.
