### ISSUE TITLE
translates :description always expects to be an array

### ISSUE THREAD

**Issue by amuntasim** [globalize/globalize#482]
Rails 4.2.5
Globalize 5.0.1

class Admission < ActiveRecord::Base
  translates :title, :description
end

create(:admission, description: 'some desc') #using factory girl
It raises
ActiveRecord::SerializationTypeMismatch: Attribute was supposed to be a Array, but was a String. -- "some desc"

changing the column name to something else i.e. :descriptions works fine.

Full trace:

ActiveRecord::SerializationTypeMismatch: Attribute was supposed to be a Array, but was a String. -- "MyString"
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/coders/yaml_column.rb:17:in `dump'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/type/serialized.rb:26:in `type_cast_for_database'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/type/mutable.rb:5:in `type_cast_from_user'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/attribute.rb:110:in `type_cast'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/attribute.rb:42:in `original_value'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/attribute.rb:37:in `value'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/attribute.rb:50:in `changed_from?'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/attribute_methods/dirty.rb:142:in `_field_changed?'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/attribute_methods/dirty.rb:115:in `save_changed_attribute'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/attribute_methods/dirty.rb:98:in `write_attribute'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/attribute_methods.rb:373:in `[]='
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/globalize-5.0.1/lib/globalize/active_record/adapter.rb:43:in `block (2 levels) in save_translations!'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/globalize-5.0.1/lib/globalize/active_record/adapter.rb:41:in `each'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/globalize-5.0.1/lib/globalize/active_record/adapter.rb:41:in `block in save_translations!'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/globalize-5.0.1/lib/globalize/active_record/adapter.rb:37:in `each'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/globalize-5.0.1/lib/globalize/active_record/adapter.rb:37:in `save_translations!'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/globalize-5.0.1/lib/globalize/active_record/instance_methods.rb:183:in `save_translations!'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:228:in `call'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:228:in `block in halting_and_conditional'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:506:in `call'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:506:in `block in call'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:506:in `each'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:506:in `call'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/callbacks.rb:306:in `_create_record'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/timestamp.rb:57:in `_create_record'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/persistence.rb:504:in `create_or_update'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/callbacks.rb:302:in `block in create_or_update'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:117:in `call'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:117:in `call'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/callbacks.rb:302:in `create_or_update'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/persistence.rb:142:in `save!'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/validations.rb:43:in `save!'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/transactions.rb:291:in `block in save!'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/transactions.rb:220:in `transaction'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activerecord-4.2.5/lib/active_record/transactions.rb:291:in `save!'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/factory_girl-4.5.0/lib/factory_girl/configuration.rb:14:in `block in initialize'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:15:in `[]'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:15:in `create'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:12:in `block in result'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `tap'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `result'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/factory_girl-4.5.0/lib/factory_girl/factory.rb:42:in `run'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:166:in `instrument'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:22:in `run'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
./spec/models/admission_spec.rb:16:in `block (3 levels) in <top (required)>'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/Users/muntasinahmed/.rvm/gems/ruby-2.1.0/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'
-e:1:in `<main>'

1 example, 1 failure, 0 passed

**Comment by shioyama** [comment]
This sounds like a question for stackoverflow, not a github issue. If you post to SO I'd be happy to try to help you.
