### ISSUE TITLE
Support activeuuid gem

### ISSUE THREAD

**Issue by phanhongphucit** [globalize/globalize#487]
I am using activeuuid (https://github.com/jashmenn/activeuuid), the primary key now is uuid type, so I could not use the helper method create_translation_table! which create foreign key as integer key.
Could you support to use this?

Thanks

**Comment by phanhongphucit** [comment]
Currently, I create the table as manual like:
create_table :ar_state_translations, :id => false do |t|
      t.uuid   :id, :primary_key => true
      t.string :name
      t.string :locale
      t.uuid   :ar_state_id

      t.timestamps
    end

**Comment by parndt** [comment]
How would you propose that we support it?

**Comment by shioyama** [comment]
Closing, feel free to re-open if you have a proposal.
