### ISSUE TITLE
Saving translated field to original table with non 'en' locale

### ISSUE THREAD

**Issue by xandrck** [globalize/globalize#497]
Hi guys.

I have problem with creating/updating original field data that have translation.

I'm using `gem 'globalize', '~> 3.1.0'` gem in my project, on `rails 3.2.22`.
I have model:

``` javascript
class Message < ActiveRecord::Base
  translates :body
end
```

I added migration to use `globalize` gem

``` javascript
class AddTranslationToMessagesBody < ActiveRecord::Migration
  def up
    Message.create_translation_table! body: :text
  end
  def down
    Message.drop_translation_table!
  end
end
```

Also I have several locales:

``` javascript
    config.i18n.available_locales = %w(en ru fr)
    config.i18n.default_locale = 'en'
```

in console I create new object with default('en') locale

``` javascript
pry :001 > m = Message.new
 => #<Message id: nil, body: nil, created_at: nil, updated_at: nil> 
pry :002 > I18n.locale
 => :en 
pry :003 > m.body = 'test'
 => "test" 
pry :004 > m.save
   (0.3ms)  BEGIN
  SQL (6.6ms)  INSERT INTO `messages` (`created_at`, `updated_at`) VALUES ('2016-03-15 12:22:02', '2016-03-15 12:22:02')
  SQL (0.4ms)  INSERT INTO `message_translations` (`locale`, `body`, `message_id`, `created_at`, `updated_at`) VALUES ('en', 'test', 1, '2016-03-15 12:22:02', '2016-03-15 12:22:02')
   (1.6ms)  COMMIT
 => true 
pry :005 > Message.last
 => #<Message id: 1, body: "test", created_at: "2016-03-15 12:22:02", updated_at: "2016-03-15 12:22:02">
```

command line shows me that object has 'body', but when I used sql to check what I got in db

``` javascript
SELECT * FROM messages;
```

I see that 'body' field is empty.

I wanna to use data from original table('messages') field('body') as default data in case when object doesn't have translation for current locale and also I wanna be able to update original field. Does `globalize` have any solution for this?

p.s. Also I tried latest `gem 'globalize', '~> 5.0.0'` with `rails '4.2.5'`. Same result.

**Comment by lbramos** [comment]
I'm also looking for a solution to force values into the original table, because I'm using "Globalize" gem to translate some fields from the "roles" table, and without values on the original table, I can't get authorization to work... Using also rolify gem and cancancan. Anyone has any idea on how to force values into the original table?

**Comment by xandrck** [comment]
@lbramos for specific cases you can use [update](http://apidock.com/rails/ActiveRecord/Relation/update) or [update_all](http://apidock.com/rails/ActiveRecord/Base/update_all/class) methods.
for example:
```javascript
role = Role.where(id: 'yor_id').update_all(original_field: 'data')
```
I do not remember for sure, also you may need to reload object.
```javascript
role.reload
```

That's not 'clean' way, but it works. But I hope there is a better way(native) to do this, because it's not comfortable to do it for each model with translations.

**Comment by lbramos** [comment]
I can't get that to work, it only updates the roles_translations table, and leaves the "roles" one with "nil" fields.... :(

`Role.first.update(name: 'teste2')`

Role Load (0.8ms)  SELECT  "roles".* FROM "roles"  ORDER BY "roles"."id" ASC LIMIT 1
   (0.2ms)  BEGIN
  Role::Translation Load (0.3ms)  SELECT "role_translations".* FROM "role_translations" WHERE "role_translations"."role_id" = $1  [["role_id", 76]]
  SQL (2.5ms)  UPDATE "roles" SET "updated_at" = $1 WHERE "roles"."id" = $2  [["updated_at", "2016-03-16 23:38:52.284725"], ["id", 76]]
  SQL (0.4ms)  UPDATE "role_translations" SET "name" = $1, "updated_at" = $2 WHERE "role_translations"."id" = $3  [["name", "teste2"], ["updated_at", "2016-03-16 23:38:52.292589"], ["id", 101]]
   (0.5ms)  COMMIT
true
 => nil

**Comment by xandrck** [comment]
Try to use `update_all`, do not update single object, because you will always update only translation field for object. Use `update_all `for collection (like I wrote above).

**Comment by lbramos** [comment]
I tried, but I get:

`undefined method `update_all' for #<Role:0x00000106ab7e38>`

**Comment by xandrck** [comment]
By using Role.first you got object.
`#Role:0x00000106ab7e38` is an object.
Find you role using `where` and you got collection.
```javascript
role_collection = Role.where(id: 'yor_id')
```
you will get result as collection of objects (with one object in it)
```javascript
[you_object]
```
then use update_all for this collection :) it should work, I test it :)

```javascript
role_collection.update_all(original_field: 'data')
```

p.s. if you will fail with it, just email me(to avoid spam in here), I will send you copy of my log how I do it.

**Comment by ridiculous** [comment]
When using the default locale, I see the column on the primary table being populated on save. However, when switching locale to something else, it doesn't write to the primary table.

**Comment by yahor** [comment]
who knows how to fix it?

**Comment by ridiculous** [comment]
@yahor I think the fix is to do what Globalize encourages, which is storing translated fields _only_ in the translations table. Trying to figure out which locale should live in the primary table as the "default" is always going to be hacky
