### ISSUE TITLE
How to safely un-globalize a model?

### ISSUE THREAD

**Issue by sebastianmarr** [globalize/globalize#507]
Hi,

I am having trouble with removing a translation table. I created the migrations with code like

```ruby
class AddTranslationTables < ActiveRecord::Migration
  def self.up
    remove_column :things, :name
    Thing.create_translation_table!({ :name => :string }, { :migrate_data => true })
  end

  def self.down
    change_table :things do |t|
      t.string :name
    end
    Thing.drop_translation_table!
  end
end
```

Now I want to remove the only translated column `name`, thus also dropping the translation table. This means

1. Removing `translates :name` from `Thing`
2. Creating a migration to drop `thing_translations`

```ruby
class DropThingTranslations < ActiveRecord::Migration
  def change
    drop_table :thing_translations
  end
end
```

Once I do the former, I cannot migrate an empty database because of

```
undefined method `create_translation_table!' for #<Class:0x007fc63a585dd8> ...
```

This happens because the `Thing` class is now missing a `translates` statement, making `create_translation_table!` unavailable.

How can I un-translate a field while still keeping my migrations working?

**Comment by cbothner** [comment]
This is why it is advised not to rely on migrations to spin up empty databases. `rake db:setup` avoids this problem by loading your `schema.rb` file, which helpfully explains its role in its comments.

```
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
```

**Comment by sebastianmarr** [comment]
You are right, I was missing exactly that feature of ActiveRecord. Thanks a lot!
