### ISSUE TITLE
Bad field type for field :payload (:json), should be :string or :text

### ISSUE THREAD

**Issue by morgler** [globalize/globalize#516]
It seems that globalize only works with :string or :text types. Is there a reason why you don't support :json?

My application is a kind of CMS, allowing the host to define content attributes dynamically (e.g. title, slug, body, …). My engine then saves all these attributes in a flexible :json column. In my mind translating :json would not be different from translating :string or :text – it should be completely transparent to globalize.

Btw: here is the "up" part of my migration:

```
def up
  MyCms::Entry.create_translation_table! title: :string, slug: :string, payload: :json
end
```

**Comment by keithlayne** [comment]
This seems like a really arbitrary restriction.  I also want to use JSON with globalize, but allowing just `:json` would still be restrictive.  I want to use `:jsonb` which makes no sense outside of postgres.  I can imagine other ways you could use this gem with other types too.  I think this restriction should be lifted to provide flexibility.

**Comment by keithlayne** [comment]
I just looked at the code and saw #538.  Instead of adding to a list every time someone wants a new (probably db-specific) type to be supported, it probably makes sense to just remove this check.
