### ISSUE TITLE
RuntimeError: can't modify frozen ActiveSupport::HashWithIndifferentAccess

### ISSUE THREAD

**Issue by sapna-prajapati** [globalize/globalize#518]
Gem is not working at all with Rails 4.2.3 and gem 'globalize', github: 'ncri/globalize'. 
While initialize the object as below:

post = Post.new(title: "Title")

it shows "RuntimeError: can't modify frozen ActiveSupport::HashWithIndifferentAccess" error always.  

class Post < ActiveRecord::Base
    translates title, :fallbacks_for_empty_translations => true
end

**Comment by ridiculous** [comment]
backtrace?

**Comment by sapna-prajapati** [comment]
Please find the configuration/codesnippet as below:
**Rails**
rails version: 4.2.3

**Migration:**
  def up
      Post.create_translation_table!  
  end

  def down
      Post.drop_translation_table!
  end

**Model**
class Post < ActiveRecord::Base
     translates title, :fallbacks_for_empty_translations => true
end

**Console**
 Post.create(title: "My First Post") OR Post.new(title: "Title")

**Error**
it shows "RuntimeError: can't modify frozen ActiveSupport::HashWithIndifferentAccess" error always.

**Comment by gfvcastro** [comment]
I have the same problem. 😕

**Comment by shioyama** [comment]
If you have questions about [ncri/globalize](https://github.com/ncri/globalize), then please ask them on the fork, not here. If they are problems with globalize/globalize, then I will re-open this.
