### ISSUE TITLE
Can't save with lock_version enabled on 5.0.1

### ISSUE THREAD

**Issue by dangnm** [globalize/globalize#523]
When I add lock_version field to my table (named "test") for Optimistic Locking, save / update function doesn't work anymore and it throws the error: 

> ActiveRecord::StatementInvalid:
> PG::UndefinedColumn: ERROR:  column "desc" of relation "test" does not exist

("desc" is my translation column on the table)
I can temporarily work around this by adding a real field named "desc" to my table but I hope that someone has a solution to fix this completely.

**Comment by shioyama** [comment]
Sorry can you explain more in detail the conditions that trigger this? What does you table schema look like?

**Comment by dangnm** [comment]
```
class Test < ActiveRecord::Base
  translates :desc, :text
end

```
It works for this case
```
- table: test
   + field: id
   + field: lock_version
   + field: desc

```

It doesn't work for this case (without the real desc column inside the table)
```
- table: test
   + field: id
   + field: lock_version

```

**Comment by shioyama** [comment]
Ok need to reproduce this and create a failing test for it. @dangnm We'll try to get to it but if you had a failing spec we'd be able to fix it faster.

**Comment by lanxichan** [comment]
got this error too. my situation:
```
Test.where(desc: 'desc') => #<Test....
```
works fine, but
```
Test.where('desc = ?', 'desc') => PG::UndefinedColumn
```
also `joins` isn't works
```
Test.joins(:test_translations).where('desc = ?', 'desc') => Association named  was not found
```

**Comment by shioyama** [comment]
@lanxichan That form of `where` (`where('desc = ?', 'desc')`) will not work with translated attributes, since it maps directly to SQL. You need to use `where(desc: 'desc')`.
