### ISSUE TITLE
Globalize is not compatible with Rails 5

### ISSUE THREAD

**Issue by hipertracker** [globalize/globalize#527]
For Rails 5.0 and gem 'globalize', '~> 5.0.0' I get the error:
```
Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    globalize (~> 5.0.0) was resolved to 5.0.0, which depends on
      activerecord (< 4.3, >= 4.2.0)

    rails (~> 5.0.0) was resolved to 5.0.0, which depends on
      activerecord (= 5.0.0)
```
This is strange. Why < 4.3? It's not what the gemspec says:

https://github.com/globalize/globalize/blob/master/globalize.gemspec#L18

**Comment by pranik** [comment]
You have to use branch **master** to work with rails 5.

Put on your Gemfile
```
gem 'globalize', github: 'globalize/globalize'
gem 'activemodel-serializers-xml'
```

**Comment by hipertracker** [comment]
Thanks, it helped.

**Comment by connorshea** [comment]
@pranik any updates on a RubyGems release with Rails 5 support?
