### ISSUE TITLE
migrate_data not working

### ISSUE THREAD

**Issue by floydj** [globalize/globalize#529]
I have a DustType model, and here's the migration I setup for Globalize:

```ruby
class TranslateDustTypes < ActiveRecord::Migration[5.0]
  def up
    DustType.create_translation_table!({
      title: :string
    }, {
      migrate_data: true
    })
  end

  def down
    DustType.drop_translation_table! migrate_data: true
  end
end
```

The migration runs ok, without any errors. 
```
== 20160713122152 TranslateDustTypes: migrating ===============================
== 20160713122152 TranslateDustTypes: migrated (0.5357s) ======================
```

But it doesn't migrate the data. 

```
mysql> select * from dust_type_translations;
Empty set (0.00 sec)
```

I'm running Rails 5, with the following in my Gemfile:

`gem 'globalize', github: 'globalize/globalize'`

Am I missing something here?

**Comment by floydj** [comment]
Sorry - I've got something deeper going on with my app. `DustType.count` in the console is report 0, but `select count(*) from dust_types` in the db is giving a number.....

**Comment by ljonny18** [comment]
Did you solve this? I'm having the same problem using Globalize and Rails 5
