### ISSUE TITLE
serialized attribute

### ISSUE THREAD

**Issue by urbanmarcin** [globalize/globalize#53]
Hi, 

I was trying to translate with globalize3 serialized attribute. After small research I realized it is impossible.  My proposition is to consider to add this functionality to globalize3.

Thanks!

**Comment by jonhue** [comment]
@parndt I am not able to make serializing translated attributes work this way:

```ruby
class Model    
  serialize :contents, Hash
  translates :contents
  translation_class.send :serialize, :contents

  # etc
end
```

What's the preferred way of doing this?

**Comment by shawila** [comment]
@jonhue I have the exact same code and adding the `translation_class.send :serialize, :contents` works fine for me

**Comment by jonhue** [comment]
@shawila 

```ruby
class Model    
  serialize :conditions, Array
  translates :title, :conditions
  translation_class.send :serialize, :conditions

  # etc
end
```

This is my exact code and I confirmed that it does not work. I repeatedly get the following exception:

> undefined method `any?' for "[\"'s_0 = 0'\", \"'v_0 = 0'\"]":String`

when interpreting the `conditions` attribute as an array.
