### ISSUE TITLE
Deprecation warning with Rails 4.2.7

### ISSUE THREAD

**Issue by mauriciopasquier** [globalize/globalize#531]
I'm getting `DEPRECATION WARNING: Modifying already cached Relation. The cache
will be reset. Use a cloned Relation to prevent this warning.` (introduced [here](https://github.com/rails/rails/commit/1b7aa62b184c4410c99208f71b59bbac5c5f03be#commitcomment-9147803)) when my code calls the `.not` method
[here](https://github.com/globalize/globalize/blob/master/lib/globalize/active_record/query_methods.rb#L6-L12) in 5.0.1. I tried cloning the scope and the warning dissapeared:

``` diff
7c7
<           if parsed = @scope.parse_translated_conditions(opts)

---
>           if parsed = @scope.clone.parse_translated_conditions(opts)
```

To be clear, my code never entered the condition. It always went to `super`, but the check is causing the warning. I'm not PRing because I don't fully understand the code and I don't have time right now to dig deeper, but all the tests are green with this change.

**Comment by shioyama** [comment]
We would be open to making this change if we have a failing test. I just tried this and can't seem to get the deprecation error you're seeing. Do you think you could write a quick test for this?

**Comment by shioyama** [comment]
e.g. using `Post` from the test data:

```ruby
Post.create(title: "foo")
Post.where.not(title: "bar")
#=> [#<Post:0x0055a1e6fc6ee8 id: 1, blog_id: nil>]
```

Seems to work fine on Rails 5.0.0.1.

**Comment by shioyama** [comment]
Sorry read the issue wrong, 5.0.1 was Globalize version and Rails version is 4.2.7. I'll check that combination.

**Comment by shioyama** [comment]
Nope, can't reproduce with AR 4.2.7 + Globalize 5.0.1 either:

```ruby
[2] pry(main)> Post.create(title: "foo")
=> #<Post:0x00557d2f4601e8 id: 1, blog_id: nil, published: nil>
[3] pry(main)> Post.where.not(title: "bar")
=> [#<Post:0x00557d2eed1790 id: 1, blog_id: nil, published: nil>]
[4] pry(main)> ActiveRecord::VERSION::STRING
=> "4.2.7"
[5] pry(main)> Globalize::Version
=> "5.0.1"
[6] pry(main)> 
```

**Comment by mauriciopasquier** [comment]
Sorry, I couldn't replicate it in a clean app.. I'll keep digging.

**Comment by mauriciopasquier** [comment]
I was finally able to pinpoint the error in a failing test for this. It happens when using `where.not` on a `has_many through: <association>` relation. In versions of rails before 5.0.0 it prints the deprecation warning I described in the first post. But from [this commit](https://github.com/rails/rails/commit/3ae98181433dda1b5e19910e107494762512a86c) onwards, it throws `ActiveRecord::ImmutableRelation`.

I believe this has more to do with the way rails checks before raising this assertion than a problem with globalize, but at least this minor (I hope) fix does away with the problem. Test and fix on my branch. Should I make a pull request?

**Comment by mauriciopasquier** [comment]
Rebased with master and PRed
