### ISSUE TITLE
Migrate data on removing a single field

### ISSUE THREAD

**Issue by davidwessman** [globalize/globalize#540]
I have a migration according to [readme](https://github.com/globalize/globalize#adding-additional-fields-to-the-translation-table)
```ruby
def up
  Event.add_translation_fields!({title: :string}, {migrate_data: true, remove_source_columns: true })
end

def down
  remove_column(:event_translations, :title, :string)
end
```

But this way I will loose my data if I rollback.
Why is there no way to do `remove_translation_fields`?

**Comment by shioyama** [comment]
I'm not sure what you would prefer to do. If you rollback the migration adding the translations fields, of course you will lose the data that was migrated to those columns.

Note that currently, the migration code leaves the original data (at the time it was migrated to the translation table) in the original column on the model table. So if your model is `Post` with table `posts` and a translated column `title`, you migrate to the column `post_translations.title` on `post_translations`, but you leave the original column on `posts` and the data that was there stays there. However subsequent updates do not get propagated to the original column so it is a snapshot in time of when you ran the migration.

However having the original column on the model table after migration causes problems and it's recommended that you remove it or move it.

In any case, reversing adding translation fields will definitely drop the translations table + fields on the table.

`remove_translation_fields` would also remove the translated attribute data, I don't see how it would be any different in that sense.

**Comment by davidwessman** [comment]
I guess it makes sense.

What I did in my latest migration was:
```
  def change
    reversible do |dir|
      dir.up do
        Category.create_translation_table!({title: :string},
                                           {migrate_data: true, remove_source_columns: true})
      end

      dir.down do
        add_column(:categories, :title, :string)
        Category.drop_translation_table!(migrate_data: true)
      end
    end
  end
```

Which I guess is what I was looking for.
