### ISSUE TITLE
Using an array data structure?

### ISSUE THREAD

**Issue by dedman** [globalize/globalize#547]
Hey guys, Is there any way to translate an array with Globalize?

i.e. if you have a Tour model that has a highlights array, which is just an array of strings. Is there anyway to use globalize with that data structure? 

Is the only workaround to add a has_many relationship so that a Tour has_many Highlights, where Highlights is a standalone model with a single field that is translatable?

**Comment by shioyama** [comment]
You're going to have to provide more detail. What is this array represeting? How are you storing it? What is its relationship with "Highlight"?

If your `Tour` model has an array of strings which each should be translated, and you want to use Globalize to manage the translations of those strings, then yes by far the easiest way would be to represent the persisted array elements as translated records. Is there any reason you wouldn't want to do that? This is pretty much the standard way you would store a one-to-many persisted relationship in any Rails application.

**Comment by dedman** [comment]
Thanks @shioyama, I'll just to add a little more detail here, so hopefully my question makes a more sense. 

Say I have a Tour model, and that tour has_many highlights, examples of a tours highlights would be sentences such as "Swim underneath a beautiful waterfall.", "Hike to the top of the beautiful volcano.". 

So if I didn't need to translate them I would usually store this sort of info in a array field on the Tour table (using postgres). I never want another tour to reference a highlight of another tour, and its very unlikely that I would need to query tours based on the highlight sentences, so using the array field makes sense, I think.

Note I also want to display the highlight sentences in different ways too, sometimes just the first 2 and then sometimes all, so I can't just have a plain text area either)

So my question is there a way to translate this array field using globalize, and thus avoid the need to create the Highlights model and its relationship to Tour?

**Comment by dalpo** [comment]
@dedman In theory, Postgres array datatype should work property with globalize.
https://github.com/globalize/globalize/blob/6c05139d7517b83e58b0e2a7fbf30fdae00dbaf1/test/globalize/attributes_test.rb#L219

Did you encounter any particular issues?

**Comment by dedman** [comment]
Hey @dalpo thanks for pointing that out, I initially just tried 

`Tour.add_translation_fields! highlights: :text, array: true` in the migration and it didn't work, however after your comment I read the code and readme further and realized it should be this. 

`Tour.add_translation_fields! highlights: {type: :text, array: true}`

Works great! Thanks for your help guys!

**Comment by adityashedge** [comment]
Adding translate for a Postgres `Array` works fine (thank you for the above solution) but when you try to run the `down` migration and convert the translations table back to an `Array` field, the `down` migration fails with error message `TypeError: can't quote Array` for `Post.drop_translation_table! migrate_data: true`

Am I missing something or this is an issue and if so can you confirm so I can send a PR for the same.
