### ISSUE TITLE
regression - create from model relation

### ISSUE THREAD

**Issue by basex** [globalize/globalize#559]
I noticed a bug when using globalize from the master branch.

This is regression bug from the last stable release.

```ruby
Comment.where(post_id: 10, user: 'test').create #=> works ok
Post.find(10).comments.where(user: 'test').create #=> ActiveModel::UnknownAttributeError: unknown attribute 'locale' for Comment.
````

This was previously working ok. Should I add a failed test?

**Comment by shioyama** [comment]
@basex Thanks! If you could add a failing spec, that would help a lot.

**Comment by shioyama** [comment]
Bisected this to #537 (and #545). @basex if you want to try fixing this, that would be greatly appreciated :wink: Otherwise I'll have a look before we release the next stable version.

**Comment by basex** [comment]
@shioyama I only started using activerecord recently so I might be unable to fix it, but I will see at least which commit created the problem.

**Comment by shioyama** [comment]
@basex No worries, I know where the problem is (9b4199bbf5f79cac290c3164547d6d5077f8e1a8), and pretty sure that passing `*args` to `super` will fix it.
