### ISSUE TITLE
You have defined translated attributes with names that conflict with columns on the model table

### ISSUE THREAD

**Issue by jonian** [globalize/globalize#562]
Hello,

I am getting this deprecation warning on Rails 5 with globalize from master branch:

```
irb(main):002:0> Page.create(title: 'Globalize Test')
DEPRECATION WARNING: You have defined translated attributes with names that conflict with columns on the model table. Globalize does not support this configuration anymore, remove or rename these columns.
Model name (table name): Page (pages)
Attribute name(s): title, content, excerpt
 (called from check_columns! at /home/jonian/.gem/ruby/2.3.0/bundler/gems/globalize-b44a06dedcb0/lib/globalize/active_record/act_macro.rb:54)
   (0.3ms)  BEGIN
   (1.4ms)  SELECT COUNT(*) FROM "pages" WHERE (slug = 'globalize-test')
  SQL (1.2ms)  INSERT INTO "pages" ("slug", "template", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["slug", "globalize-test"], ["template", "default"], ["created_at", 2016-10-06 09:17:57 UTC], ["updated_at", 2016-10-06 09:17:57 UTC]]
  SQL (1.1ms)  INSERT INTO "page_translations" ("page_id", "locale", "created_at", "updated_at", "title") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["page_id", 20], ["locale", "en"], ["created_at", 2016-10-06 09:17:57 UTC], ["updated_at", 2016-10-06 09:17:57 UTC], ["title", "Globalize Test"]]
   (2.7ms)  COMMIT
=> #<Page id: 20, slug: "globalize-test", thumbnail_id: nil, template: "default", created_at: "2016-10-06 09:17:57", updated_at: "2016-10-06 09:17:57", video_id: nil>
```

Model:

```
class Page < ApplicationRecord
	# Enable globalize
	translates :title, :content, :excerpt, fallbacks_for_empty_translations: true
	globalize_accessors
end
```

Migration:

```
class CreatePages < ActiveRecord::Migration
  def up
    create_table :pages do |t|
      t.string :title
      t.string :slug
      t.text :content
      t.text :excerpt
      t.integer :thumbnail_id
      t.integer :video_id
      t.string :template

      t.timestamps null: false
    end
    add_index :pages, :slug, unique: true
    Page.create_translation_table! title: :string, content: :text, excerpt: :text
  end

  def down
    drop_table :pages
    Page.drop_translation_table!
  end
end
```

I recently updated this from globalize 5.0.1 and Rails 4.2.6.

**Comment by shioyama** [comment]
That's a deprecation warning from Globalize, added in #557, to warn users that having a model table which has a column with the same name as a translated attribute is not encouraged (with your migrations above you will get `title` and `content` in both `pages` and `page_translations`). We're planning to add more info in the readme but just haven't done that yet.

The problem is that this configuration is much more likely to confuse ActiveRecord and result in strange bugs and query results. We've tried to mitigate that to some degree (actually in Rails 5 it should be fine since we just completely ignore the model table column), but if you have no reason to have the column there, please either remove it or rename it.

Either way, in your configuration above, Globalize will completely ignore `pages.title` and `pages.content`.

**Comment by shioyama** [comment]
I closed the issue because this is not a bug. However we may remove the deprecation for Rails 5 applications since as noted I think we now handle the situation better. Is there any reason you want those columns there?

**Comment by jonian** [comment]
@shioyama Thanks for the quick response and the detailed explanation.

The application models where created before adding globalize and I did not remove the columns in the pages table. I will remove them now.

**Comment by anthony-robin** [comment]
How does it works with the `friendly_id`gem ? 
As I know, `friendly_id` expects a `slug` column in both tables so how the link can be make if we remove it in the no translations tables ?

**Comment by shioyama** [comment]
@anthony-robin You mean the `slug` column is translated and friendly id won't work unless it's in the model table (as well as the translation table)?

If so, then that's a problem. But I don't see why that should be necessary.

**Comment by anthony-robin** [comment]
@shioyama Yes it is. If I removed the `slug` in the model table all finders are broken throwing error 
`ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'posts.slug' in 'where clause’:`

I am using the last `FriendlyId` and `FriendlyIdGlobalize` gem version available at this time

**Comment by shioyama** [comment]
@anthony-robin Which version of Rails are you using?

**Comment by anthony-robin** [comment]
@shioyama I am using the Rails 5.0.0.1 version, but I think this error happened as well in 4.2.7.1

**Comment by anthony-robin** [comment]
In `FriendlyIdGlobalize` code, it's explained that slug column must be set in both tables: https://github.com/norman/friendly_id-globalize/blob/master/lib/friendly_id/globalize.rb#L16

**Comment by shioyama** [comment]
@anthony-robin Thanks, that's clearly going to be a problem then... Globalize has had issues with that configuration since Rails 4 or so. I'm not sure how we can fix this one.

**Comment by shioyama** [comment]
`friendly_id-globalize` is a very small gem, maybe we can find a way to make it not require the slug on the model table. That might be easier than changing Globalize to handel the model table slug.

**Comment by anthony-robin** [comment]
I agree, it could be good to find a workaround with `friendly_id-globalize`. 
However, I'm not sure the gem is still maintained and the FriendlyId core didn't get any version since almost two years.
Maybe I should open the issue to the gem repository as well ?
