### ISSUE TITLE
String SQL snippet conditions on translated attributes are not forming proper query, whereas hash syntax of the same query works fine

### ISSUE THREAD

**Issue by SakthiGurunathan07** [globalize/globalize#572]
Rails verison : 4.2.7.1
Globalize version: 5.0.1

Example:

``` ruby
class User < ActiveRecord::Base
 translates name
end
```

``` ruby
User.where("name=?", "Self")
```

is not working
query generated:

``` sql
"SELECT `users`.* FROM `users` WHERE (name='Self')"
```

 where as,

``` ruby
User.where(name: "Self")
```

is working fine.  

query generated: 

``` sql
"SELECT `users`.* FROM `users` INNER JOIN `user_translations` ON `user_translations`.`user_id` = `users`.`id` WHERE `user_translations`.`name` = 'Self' AND `user_translations`.`locale` = 'en'"
```

@parndt : Could you please help me with this ?

**Comment by parndt** [comment]
Wow, you know, I've never used strings for this.  Do you have a compelling reason why you want to use strings instead?

**Comment by SakthiGurunathan07** [comment]
@parndt  Yes it is large application and it is difficult to convert all the existing codes to hash syntax .

**Comment by parndt** [comment]
Unfortunately the case you're hitting up against is this one.. if I put a pry console inside [the relevant parse_translated_conditions method in globalize](https://github.com/globalize/globalize/blob/master/lib/globalize/active_record/query_methods.rb#L44-L50):

```ruby
    45: def parse_translated_conditions(opts)
    46:   require "pry";
 => 47:   binding.pry
    48:   if opts.is_a?(Hash) && respond_to?(:translated_attribute_names) && (keys = opts.symbolize_keys.keys & translated_attribute_names).present?
    49:     opts = opts.dup
    50:     keys.each { |key| opts[translated_column_name(key)] = opts.delete(key) || opts.delete(key.to_s) }
    51:     opts
    52:   end
    53: end

[1] pry(#<Refinery::Page::ActiveRecord_Relation>)> opts
=> "title = ?"
```

Then you can see that the options are not a Hash, which is what we're looking for.  I feel like it'd really complicate the parser to add support for strings like this, but what do you think @shioyama ?

**Comment by SakthiGurunathan07** [comment]
@parndt  The same query works fine in rails 4.1.15 and globalize "4.0.3". I couldn't find any change in parse_translated_conditions method between globalize 4.0.3 and 5.0.1.  Whether we have to make any patch for compatible for Rails 4.2

**Comment by dalpo** [comment]
@SakthiGurunathan07 Strange behaviour...
Maybe in the old version of Globalize the `translations` relation were eager loaded. 

If you try with `User.join_translations.where("name=?", "ABC")` it should work

**Comment by shioyama** [comment]
@parndt I'm against making that patch any more complicated, it's already pretty tricky as-is.

@dalpo There was a change a while back in how translations were eagerly loaded (changed to `preload` I believe). I'm  not sure if that's related. It may also be that rails used to convert string queries to a hash which the patch could handle.

@SakthiGurunathan07 You're right to highlight that it's a kind of regression, but I personally never would have expected the string query to work with translated attrigutes. In you case can you use a hash instead?

Unless this is easy to fix, I'd suggest just making a note in the readme mentioning the limitation of the query patch.

**Comment by SakthiGurunathan07** [comment]
@shioyama The system I m working on is a very huge application and it is very difficult to find all the places where queries have string snippets instead of hash. Also I made few observations , When I used string queries on the records which are created when app was using rails 4.1 and globalize "4.0.3" it works fine as expected. But records created with rails 4.2 and globalize 4.0.3 are not working.  Also I make a note here that both the translated attribute column and actual table column both have same name.  Can you help me with troubleshooting the issue? Is this a problem related to eager load ?

@dalpo  I will check your fix and if it works i will check with a patch in QueryMethods "where" method

**Comment by shioyama** [comment]
Having a model table column with the same name as the translation table column is going to cause problems. Can you remove the model table column or rename it? Globalize doesn't need it anyway.

**Comment by SakthiGurunathan07** [comment]
@shioyama  As you suggested I removed model table column and tried but it doesn't help. I tried to ran the below query in rails 4.1 and queries fired shows the issue is related to preload . 
`  Actual Query:
  User.where("name=?", "Self")

  Generated Queries:
  User Load (1.5ms)  SELECT `users`.* FROM `users`  WHERE (name='Self')
  User::Translation Load (1.4ms)  SELECT `user_translations`.* FROM `user_translations`  WHERE `user_translations`.`user_id` = 1
  User::Translation Load (0.5ms)  SELECT `user_translations`.* FROM `user_translations`  WHERE `user_translations`.`user_id` = 6
  User::Translation Load (0.6ms)  SELECT `user_translations`.* FROM `user_translations`  WHERE `user_translations`.`user_id` = 11`

The issue is that if string SQL snippet is written using translated column attribute then preloading translated records is not working where as string queries for un-translated attributes  are able to preload translated records.


@dalpo I am not able to call join_translations on User model . It throws method not defined.

**Comment by SakthiGurunathan07** [comment]
@shioyama , @dalpo , @parndt  Have you guys got any hint on this issue ?

**Comment by dalpo** [comment]
Sorry @SakthiGurunathan07, I'm lacking of free time during this week...
Btw, the `join_translations` works only with `ActiveRecord::Relation` an so you can't call it direclty on the model but eventually on a query scope. 

For instance:
` User.where("name=?", "Self").join_translations` should work.
` User.join_translations.where("name=?", "Self")` should NOT work.

Anyway you can obtain the same result using the `with_translations` method witch works in both the cases :)

For instance:
` User.where("name=?", "Self").with_translations` should work.
` User.with_translations.where("name=?", "Self")` should work too.

If you **really** want to restore the old behavior of globalize, you could try to put a `default_scope` into your models with the `with_translations` scope.

```
default_scope { with_translations }
```

But personally I never recommend the use of `default_scope`... So I suggest you to fix your queries and use the `with_translations` scope only where you really need it.

**Comment by shioyama** [comment]
I'm wondering if 62e4789e is what broke support for string queries with translated attributes. Note the commit message: "Support for strings is wilfully ommitted."
