### ISSUE TITLE
NoMethodError (undefined method `name' for nil:NilClass)

### ISSUE THREAD

**Issue by jon3dc** [globalize/globalize#584]
'activerecord', '4.0.0'
'globalize', '4.0.3'

Hi, I am experiencing the following exception when updating a model with a joine (has_many) on a translated model (in this case department): 
```
NoMethodError (undefined method `name' for nil:NilClass):
  app/models/employee.rb:741:in `department_tokens='
  app/controllers/employees_controller.rb:274:in `block in update'
  app/controllers/employees_controller.rb:273:in `update'
```

I am not sure how much of the following is relevant / needed to document here :) however: In this example an employee can have many departments: 
```
has_many :department_employee_ships, :dependent => :destroy	
has_many :departments, :through => :department_employee_ships, :source => :department
```

The department model is translated: 
`translates :name, :description`

This may not be related to the Globalize gem but worked fine until it was added ...

Any help / advice would be greatly appreciated !

**Comment by ridiculous** [comment]
Might be your app code/usage. What does the `department_tokens=` method defined in "app/models/employee.rb:741" look like? That's where the exception is occurring.

**Comment by jon3dc** [comment]
Hi thanks for the reply: 

```
attr_reader :department_tokens
def department_tokens=(ids)
	self.department_ids = ids.split(",")
end
```
