### ISSUE TITLE
localize with more than locale

### ISSUE THREAD

**Issue by toneplex** [globalize/globalize#592]
I'm wondering if anyone had any pointers on how to accomplish localizing on more than just locale. If I wanted to extend globalize to use locale, county, state & city as localization fields, what would need to be changed?

For example:

Post( title: 'hello from US NY New York', county: 'US', state: 'NY', city: 'New York', locale: en)
Post( title: 'こんにちは、米国NYニューヨークから', county: 'US', state: 'NY', city: 'New York', locale: ja)
Post( title: 'hello from US MA Boston', county: 'US', state: 'MA', city: 'Boston', locale: en)

**Comment by mingsheng88** [comment]
I have a same question:
https://stackoverflow.com/questions/44621853/assign-not-update-translation-enabled-activerecord-to-work-with-activerecord-i
