### ISSUE TITLE
Where with ilike -> column "name" does not exist

### ISSUE THREAD

**Issue by shadowed87** [globalize/globalize#599]
I'm using rails 5 and globalize master.

Migrations worked flawlessly, and I migrated existing data, removing the original column from the table.

Records are created correctly, and it is possible to find them with 
Post.where(name: 'Test')
Post.find_by(name: 'Test')

However, when using the ilike operator against the name attribute, with the following:
Post.where("name ilike ?", '%Test%')

It doesn't look inside the translations tables. 

Post Load (1.5ms)  SELECT "posts".* FROM "posts" WHERE (name ilike '%Test%')
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "name" does not exist

Is it supposed to be like this?

**Comment by shadowed87** [comment]
I ended up adding to all my models the following default_scope, in order to force loading for translations with the locale.

  default_scope { joins(:translations).where('locale = ?', I18n.locale) }

**Comment by shadowed87** [comment]
Actually using the default_scope was a very bad idea...

I ended-up patching a bit globalize, in case a string is passed, handling the ilike through parse_translated_conditions

https://github.com/shadowed87/globalize/commit/c8ef929a721becfbdaf61916654e7da86b842aea

**Comment by ridiculous** [comment]
Yes, default scopes are almost never a good idea 😆 And Globalize purposefully does not support strings. Imagine trying to expand your patch to include every possible SQL operator!
