### ISSUE TITLE
Bug on count following an order

### ISSUE THREAD

**Issue by basex** [globalize/globalize#608]
The commit https://github.com/globalize/globalize/commit/f1f1628f00fd69c1ad90121496f339299525f890 introduced an error when a `count` is done following an `order`.

Example:
```ruby
products = Product.order(:name)
products.count #=>   DEBUG -   (1.6ms)  SELECT COUNT(*, product_translations.name) FROM `products` INNER JOIN `product_translations` ON `product_translations`.`product_id` = `products`.`id` WHERE `product_translations`.`locale` = 'en'
ActiveRecord::StatementInvalid: Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' product_translations.name) FROM `products` INNER JOIN `product_translations` ON' at line 1: SELECT COUNT(*, product_translations.name) FROM `products` INNER JOIN `product_translations` ON `product_translations`.`product_id` = `products`.`id` WHERE `product_translations`.`locale` = 'en'
```

**Comment by basex** [comment]
I'm having other errors with this commit:
```ruby
Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1: SELECT DISTINCT COUNT(DISTINCT #<struct Arel::Attributes::Attribute relation=#<Arel::Table:0x0000000885aa18 @name="products", @columns=nil, @type_caster=#<ActiveRecord::TypeCaster::Map:0x0000000885aa68 @types=Product(id: integer, price: float)>, @table_alias=nil>, name="*">, product_translations.name) FROM `products` INNER JOIN `product_translations` ON `product_translations`.`product_id` = `products`.`id` WHERE `product_translations`.`locale` IN ('pt', 'en')
```

**Comment by ckornaros** [comment]
I make the same test but with postresql and I have the same issue :(
`products = Product.order(:name)
products.count 
  (9.3ms)  SELECT DISTINCT COUNT(DISTINCT #<struct Arel::Attributes::Attribute relation=#<Arel::Table:0x0055de7fc5d718 @name="products", @engine=Product(id: integer, created_at: datetime, updated_at: datetime, image_id: integer, category: string), @columns=nil, @aliases=[], @table_alias=nil, @primary_key=nil>, name="*">, product_translations.name) FROM "products" INNER JOIN "product_translations" ON "product_translations"."product_id" = "products"."id" WHERE "product_translations"."locale" IN ('fr', 'tig')
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "Arel"
LINE 1: SELECT DISTINCT COUNT(DISTINCT #<struct Arel::Attributes::At...
                                                ^
: SELECT DISTINCT COUNT(DISTINCT #<struct Arel::Attributes::Attribute relation=#<Arel::Table:0x0055de7fc5d718 @name="products", @engine=Product(id: integer, created_at: datetime, updated_at: datetime, image_id: integer, category: string), @columns=nil, @aliases=[], @table_alias=nil, @primary_key=nil>, name="*">, product_translations.name) FROM "products" INNER JOIN "product_translations" ON "product_translations"."product_id" = "products"."id" WHERE "product_translations"."locale" IN ('fr', 'tig')
	from /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
	from /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
	from /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
	from /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
	from /usr/local/bundle/gems/schema_plus_core-1.0.0/lib/schema_plus/core/active_record/connection_adapters/postgresql_adapter.rb:57:in `block in exec_no_cache'
	from /usr/local/bundle/gems/modware-0.1.2/lib/modware/stack.rb:55:in `call_implementation'
	from /usr/local/bundle/gems/modware-0.1.2/lib/modware/stack.rb:85:in `_modware_continue'
	from /usr/local/bundle/gems/modware-0.1.2/lib/modware/stack.rb:77:in `_modware_call'
	from /usr/local/bundle/gems/modware-0.1.2/lib/modware/stack.rb:44:in `execute'
	from /usr/local/bundle/gems/modware-0.1.2/lib/modware/stack.rb:20:in `start'
	from /usr/local/bundle/gems/schema_monkey-2.1.3/lib/schema_monkey/stack.rb:34:in `start'
	from /usr/local/bundle/gems/schema_plus_core-1.0.0/lib/schema_plus/core/active_record/connection_adapters/postgresql_adapter.rb:56:in `exec_no_cache'
	from /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
	from /usr/local/bundle/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
... 12 levels...
	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/bundle/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /var/www/qoqa4/bin/rails:9:in `<top (required)>'
	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'`

**Comment by adamtao** [comment]
I found that using a string instead of a symbol as the order argument made the error go away. As in `order('name')` instead of `order(:name)`

Not really a fix so much as a clue. Both should work.

**Comment by basex** [comment]
@dalpo @parndt can I revert https://github.com/globalize/globalize/commit/f1f1628f00fd69c1ad90121496f339299525f890 ? The commit is creating problems both in MySQL and Postgresql when other methods are chained after a loaded collection with an order.

Source of the problem:
```ruby
full_column = translated_column_name(column)

# Inject `full_column` to the select values to avoid
# PG::InvalidColumnReference errors with distinct queries on Postgres
if select_values.empty?
   self.select_values = [Arel.star, full_column]
else
   self.select_values << full_column
end
```

**Comment by basex** [comment]
I tried `"#{table.table_name}.#{Arel.star}"`instead of `self.arel_table[Arel.star]`, but other methods, for example in `ActiveRecord::Calculations`, don't work with `Arel.star` + another field.

`PG::InvalidColumnReference` seems to be a problem coming from Rails, not sure if you should correct that here. 

References: https://stackoverflow.com/questions/42846286/pginvalidcolumnreference-error-for-select-distinct-order-by-expressions-mus and https://github.com/rails/rails/issues/28890

**Comment by dalpo** [comment]
@basex I'm sorry but currectly I don't have enough time to work on this bug.

Anyway, you can workaround this strange behaviour using the syntax: `Product.with_translations.order('product_translations.name').count`

**Comment by basex** [comment]
@dalpo the problem is not only with the count. If you have a big codebase using scopes with order is very difficult to find all the problem cases. Wouldn't it be easier to revert the commit for now? I can do it if agreed.

**Comment by peterfication** [comment]
For me, the count failed because of the select of globalize. I had `...unscope(:order)` but this was not enough. So I put also `...unscope(:select)` before the count method.
