### ISSUE TITLE
associations in translations table

### ISSUE THREAD

**Issue by pinkynrg** [globalize/globalize#614]
I was wondering if it was possibile to have integer foreign keys instead of strings as my translated field and then have a rails association linked to it (for example belongs_to). 

I have a measurement_types table (like mass, length, volume, ...) and I would like to set the default measurement_unit for every type based on the locale.

- mass with Usa locale would return pound.
- mass with Italian locale would return kg.

**Comment by AleOnRails** [comment]
I've the same problem.
My model look like this

```
class Car < ApplicationRecord
  belongs_to :wheel
  translates :whee_id
end

class Wheel < ApplicationRecord
  has_many :cars
end
```

writing `Wheel.first.cars` i have
```
 Car Load (0.3ms)  SELECT `cars`.* FROM `cars` WHERE `cars`.`wheel_id` = 1
(pry) output error: #<ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'crs.wheel_id' in 'where clause': SELECT `cars`.* FROM `cars` WHERE `cars`.`wheel_id` = 1>
```

**Comment by pinkynrg** [comment]
@AleOnRails not sure if out problem is the same but, at the end I monkey patched the Cart model something like:

```ruby
class Car < ApplicationRecord

## monkeypatch
def wheel
   self.translation.wheel
end

class Wheel::Translation
   belongs_to :wheel
end
```

let me know if it helps
