### ISSUE TITLE
Release 5.1.0 ?

### ISSUE THREAD

**Issue by ckornaros** [globalize/globalize#618]
Hi,
We really need this feature "Add RequestStore to make Globalize thread-safe again #420" which will be released in 5.1.0

Have you a date for this release ?

Thanks for your answer !

**Comment by parndt** [comment]
Have you used the pre release gem? Does it work?

**Comment by wakeless** [comment]
The prerelease gem on rubygems is < 5.1. Is this the right gem to be testing?

https://rubygems.org/gems/globalize/versions/5.1.0.beta1

**Comment by ckornaros** [comment]
@parndt Yes we used the pre release gem and it works great. It fixed issues we have with concurrents threads (locale was randomly set when we sent newsletters in different locales).

**Comment by basex** [comment]
Since this commit https://github.com/globalize/globalize/commit/f1f1628f00fd69c1ad90121496f339299525f890 I was not able to upgrade any more, it created problem with code that was previously working. I put the issue here: https://github.com/globalize/globalize/issues/608

**Comment by ckornaros** [comment]
@basex I make the same test but with postresql and I have the same issue :(

**Comment by bricesanchez** [comment]
Could we release another pre-release (eg. 5.1.0.beta2)? 

5.1.0.beta1 on rubygems was released on March 10, 2017 and support for Rails 5.1 was added on April 28, 2017 

See: https://github.com/globalize/globalize/commit/177083fb4ad9bdd231402be7f7a2722df6a7fe7c

**Comment by parndt** [comment]
There you go @bricesanchez

**Comment by manuelmeurer** [comment]
How close are we to v5.1.0?
Which issues need to be fixed before the release?

**Comment by Kjir** [comment]
The instructions in the README still suggest to use the latest master for Rails 5 support, reading this issue I discover that actually there are at the very least pre-releases... So I'd suggest to update the README — which would need to be done for the actual release anyway.

**Comment by parndt** [comment]
Can everyone let me know how the pre release gems are working for them? That'd help us to gain confidence for 5.1.0 final

**Comment by Kjir** [comment]
I'm in the process of upgrading an old application from rails 4.2 to the greatest version of rails I can get to work. I'll let you know what are my results, but so far most of the tests pass, so that's a good sign.

**Comment by awaltman** [comment]
I upgraded a Rails 4.2 application to Rails 5.1, including changing from globalize 5.0.1 to 5.1.0.beta2. Everything has passed regression testing and we're on track to deploy to production. For our application, we experienced no issues with 5.1.0beta2.

**Comment by parndt** [comment]
@Kjir thank you, keen to hear final result 😄 
@awaltman thank you so much!

**Comment by benhutton** [comment]
@parndt we've been running `5.1.0.beta2` in production since July 31, 2017, on a large app with no known errors. We ran it off a `ref` (`6f9d3f38d132f3e5dcbe33311674e696c922d23c`) for 3 months prior to that and upgraded once we realized a pre-release gem had been cut.

I say :shipit:!

**Comment by parndt** [comment]
👍 all done - thanks everyone, it's reassuring to have reports from people of actual success

**Comment by biow0lf** [comment]
@parndt can you push release 5.1.0 tag to repo?

**Comment by Kjir** [comment]
I finished the upgrade, the code is still not deployed, but so far everything looks perfect! Thanks!!

**Comment by parndt** [comment]
@biow0lf done, thanks!
