### ISSUE TITLE
Model `attribute_names` missing translated attributes, but only sometimes

### ISSUE THREAD

**Issue by indirect** [globalize/globalize#624]
Somehow, the act of calling `ActiveRecord::Base.connection` results in one (and only one) model having any translated attributes removed from its list of attributes. Models with translations after the first seem to be fine, and requiring the model file rather than allowing autoload to trigger also seems to be fine.

If this bug triggers, however, it causes a huge number of deprecation warnings that look exactly like the deprecation warnings generated by the Globalize test suite:

```
DEPRECATION WARNING: title is not an attribute known to Active Record. This behavior is 
deprecated and will be removed in the next version of Rails. If you'd like title to be 
managed by Active Record, add `attribute :title to your class. (called from write at 
/home/travis/build/indirect/globalize/lib/globalize/active_record/adapter_dirty.rb:20)
```

The deprecation warning is triggered by `adapter_dirty.rb:20` calling `attribute_will_change!` with an attribute name that has been added to `ignored_columns` by [adding ignored columns](https://github.com/globalize/globalize/blob/master/lib/globalize/active_record/act_macro.rb#L43-L46).

I tried to use your issue template, but the problem seems to be resolved by defining the model class that has translated attributes, so I could only reproduce it in a minimal rails app with a script:

https://github.com/indirect/globalize-missing-columns-demo/blob/master/bin/reproduction

It seems like I can solve my particular problem by outright deleting [lines 43 to 46](https://github.com/globalize/globalize/blob/master/lib/globalize/active_record/act_macro.rb#L43-L46), but that breaks tests, even though it's not clear to me at all why this ignoring is a good thing. Can anyone tell me is happening here, exactly, and why am I ending up with models that generate a billion AR deprecations?

**Comment by ArmadilloXX** [comment]
Faced the same issue with lot of deprecation warnings. I think it's a part of Rails 5 Attributes API, when we need to declare them explicitly, as described in the message above. 

In Rails 5 new [AR:Base.has_attribute?](https://github.com/rails/rails/commit/4294a7eebf52759be61ed57908436d6324f26120) has been presented. This method is being used [here](https://github.com/rails/rails/blob/1c275d812f35f53f93cd96184a4f319983766cc5/activerecord/lib/active_record/attribute_methods/dirty.rb#L275-L288) and now it checks presence of attributes through `attributes_types` hash. I've played a little bit with it and it seems to me that using `attribute_names` is no longer works to properly define an attribute. I do not have enough time now to dive deeper and understand how it would impact Globalize internals for translated attributes definitions, but as I mentioned above using explicit attribute declaration works fine to remove all the warnings.

As for `ignored_columns` I think it's a good way to [protect](https://github.com/globalize/globalize/blob/master/lib/globalize/active_record/act_macro.rb#L49-L60) you from having the same columns in parent model and translation table.

**Comment by elbarto132** [comment]
+1

**Comment by waldyr** [comment]
+1

**Comment by pacuna** [comment]
Yes, pretty annoying when running tests

**Comment by facetostool** [comment]
+1

**Comment by alexandre025** [comment]
+1

**Comment by antonwestman** [comment]
+1

**Comment by fho-wtag** [comment]
+1

**Comment by amclelland** [comment]
+1

**Comment by charlesdg** [comment]
+1

**Comment by Mikopet** [comment]
+1

**Comment by factor4** [comment]
+1

**Comment by elct9620** [comment]
+1

**Comment by giedriusr** [comment]
Same here. Any updates on this? When will it be fixed?

**Comment by fbsr** [comment]
+1

**Comment by FaisalChoura** [comment]
+1

**Comment by VitaliyAdamkov** [comment]
+1

**Comment by PaulBrunache** [comment]
+1 
any word on this yet ?

**Comment by jlerpscher** [comment]
+1

**Comment by tbilous** [comment]
+1

**Comment by DaniG2k** [comment]
+1

**Comment by PaulBrunache** [comment]
is there a workaround for this ?

**Comment by adamtao** [comment]
In your models that use translations, you can declare the missing attribute with an extra line like this:

translates :name
attribute :name

**Comment by Kjir** [comment]
On my project this is kind of a deal breaker: I get hundreds of such warnings and apparently I've been unable to work around them with the `attribute` declarations

**Comment by Circuit8** [comment]
+1

**Comment by yahor** [comment]
+1

**Comment by pplant** [comment]
+1

**Comment by rpbaptist** [comment]
I monkey patched this:

```ruby
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  # Rails 5.1 requires each non database attribute to be specified.
  #
  # This means every attribute which is translated by Globalize needs to be
  # declared with class method `attribute`.
  #
  # This could be removed if Globalize fully supports Rails 5.1
  class << self
    def translates(*attr_names)
      attr_names.each { |attr_name| attribute attr_name }

      super
    end
  end
end
```

**Comment by arkhamRejek** [comment]
@rpbaptist thanks dude! You're the man

**Comment by n-rodriguez** [comment]
I thinks this issue can be closed : it's fixed since https://github.com/globalize/globalize/pull/629
