### ISSUE TITLE
Translates doesn't get along with uniqueness validations in Postgresql

### ISSUE THREAD

**Issue by waldyr** [globalize/globalize#625]
I've created a simple demo app with two commits. The first initial commit which sets up an rails 5.1 app with globalize. The second one introduces the `translates` into the post model and a bug (there's only one test in the whole app). Gemfile.lock is included so you can check the versions used.

Here's the output of rake. You just need to clone, `rails db:create db:migrate` and rake to see it.

```
❯ bundle exec rake
Run options: --seed 61715

# Running:

E

Error:
PostTest#test_the_truth:
ArgumentError: wrong number of arguments (given 4, expected 3)
    test/models/post_test.rb:5:in `block in <class:PostTest>'


bin/rails test test/models/post_test.rb:4



Finished in 0.116156s, 8.6091 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

Here's the link to the demo app https://github.com/waldyr/globalize_bug. Ping me if you need anything else. In the mean time this bug is solved how can I bypass this issue?

**Comment by robotex82** [comment]
Im having the same problem. Did you solve it?

**Comment by waldyr** [comment]
https://github.com/globalize/globalize/pull/619 Use this fork or wait for it to be merged.
