### ISSUE TITLE
uniqueness_validator broken with Rails 5.1

### ISSUE THREAD

**Issue by elbarto132** [globalize/globalize#626]
in the file /lib/patches/active_record/rails5/uniqueness_validator.rb:9
you find this call: relation = build_relation(finder_class, finder_table, attribute, value).where(locale: Globalize.locale)

In Rails 5.0 this method looked like this: def build_relation(klass, table, attribute, value)
In Rails 5.1 it now looks like this: def build_relation(klass, attribute, value)
In /activerecord-5.1.1/lib/active_record/validations/uniqueness.rb:52

Thus it throws ArgumentError: wrong number of arguments (given 4, expected 3)

**Comment by waldyr** [comment]
https://github.com/globalize/globalize/pull/619
