### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by gustavovnicius** [globalize/globalize#628]
So, I'm experiencing this issue #562 with AR 5+
And I saw that it was already fixed here: https://github.com/globalize/globalize/blob/master/lib/globalize/active_record/act_macro.rb#L55
But still, this version wasn't published yet, so I'm wondering when it will be, because that deprecation error is really annoying.

**Comment by matiasgarciaisaia** [comment]
Is there anything we can help with to get a new release published? Hitting #601 here - fixed in #602 a while ago :)

**Comment by cars10** [comment]
Any updates on this?

**Comment by parndt** [comment]
https://rubygems.org/gems/globalize/versions/5.2.0 :smile:
