### ISSUE TITLE
Deprecation of active_support/dirty methods in callbacks Rails 5.1

### ISSUE THREAD

**Issue by dsounded** [globalize/globalize#636]
Thanks for the gem !

`DEPRECATION WARNING: The behavior of `attribute_change` inside of after callbacks will be changing in the next version of Rails.`

in `5.1.0.beta2`, any plan to fix it up ? Because we use it in callbacks and all the tests spam this message over and over again

**Comment by basex** [comment]
Related https://github.com/globalize/globalize/issues/607
This dirty change attributes don't seem to be working 100% on the last release.

**Comment by dsounded** [comment]
@basex  So, is it better to use `beta1` branch ?
