### ISSUE TITLE
Duplicate models when using order on fallbacked globalized column

### ISSUE THREAD

**Issue by kreintjes** [globalize/globalize#642]
When using order on a globalized column in a relation, the same entry is returned multiple times. This only happens for a fallbacked locale, but I18n fallbacks is the default in the production environment in Rails applications (`config.i18n.fallbacks` is set to true).

So suppose we have a Post model with a translated attribute title. We create some entries for it with both an :en and :nl translation. When I have my default locale set to :en, but the current I18n locale is :nl (and i18n.fallbacks is enabled) and I run `Post.order(:title)`, I would expect every object to be returned once, but instead I get every object twice. Manually adding a distinct to the relation does not fix the problem.

The problem can be circumvented by adding a `with_translations(I18n.locale)` scope. So `Post.with_translations(I18n.locale).order(:title)` works. However, this breaks the fallback feature, since only the current locale translations are requested.

Disabling fallbacks completely is also a workaround, but of course this also breaks the fallback functionality.

I have created a MiniTest bug test to demonstrate the various situations and the issue: https://gist.github.com/kreintjes/13a96050455c0f3a09ae2430ad36c079

I am using Globalize 5.1.0.beta2 with Rails 5.0.4 and Ruby 2.4.1. I have also tried this against Globalize 5.0.1. This results in an "no such column: post_translations.title" exception since the translations are not automatically joined when ordering. When adding the with_translations scope (without specifying the locale), the same problem occurs.

**Comment by frederickdubois** [comment]
I'm also encountering this problem, it's really problematic...

**Comment by ljonny18** [comment]
+1 having the same issue !

**Comment by yboulkaid** [comment]
I'm also seeing the same issue

**Comment by nitin-cis** [comment]
I am facing the same issue

**Comment by rvfx** [comment]
This is definitely a problem. Each use of the translation table in a query will return multiple instances. Since there is no real `DISTINCT ON` functionality in Rails, you have to add `.uniq` to the end of your query. This will make the result an array.
