### ISSUE TITLE
Scope entries without translations

### ISSUE THREAD

**Issue by musixite** [globalize/globalize#648]
Model Page
Model PageTranslations
page_status 1:draft, 2:edit, 3:published
title
body

I have 2 forms (on separate pages):
English form (default)
French translation

When a page is created, only the English version is saved.

I want to implement a list that only shows the French pages with a status of 1 or 2 OR which don't exist yet (no French entry in the PageTranslations table). In other words, I want a list with the pages that need a translation or aren't published.

Is there a way to make such a query?

Thanks!
Vincent

**Comment by FiloSpaTeam** [comment]
I'm doing a similar works. You can check my repo to see how i worked with available_translations :+1: 
https://github.com/UnitooTeam/unitoo.site
