### ISSUE TITLE
Deprecation warning on `changed?`

### ISSUE THREAD

**Issue by mkmiller** [globalize/globalize#653]
When calling the ActiveRecord override `changed?` under Rails 5.1, it can generate many deprecation warnings similar to:

> DEPRECATION WARNING: The behavior of `changed_attributes` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_changes.transform_values(&:first)` instead. (called from changed? at /Users/user/.rvm/gems/ruby-2.3.3/bundler/gems/globalize-b22845506598/lib/globalize/active_record/instance_methods.rb:169)

**Comment by thilonel** [comment]
I have so many issues because of this on the app that I can't see anything on the test output...

**Comment by VitaliyAdamkov** [comment]
```
module ActiveRecord
  module AttributeMethods
    module Dirty
      private

      def emit_warning_if_needed *args
      end
    end
  end
end
```
Put it in initializer & forget about warnings

**Comment by thilonel** [comment]
Well thank you, but I also want to upgrade to Rails 5.2 :D
