### ISSUE TITLE
globalize depends on wrong cldrjs version

### ISSUE THREAD

**Issue by Kynde** [globalize/globalize#667]
Steps to reproduce:
```
# yarn add globalize
# grep cldrjs yarn.lock
cldrjs@^0.4.6
...
# grep vers node_modules/cldrjs/package.json 
  "version": "0.4.8"
```

The problem is that globalize depends on "^0.4.6" and the cldrjs has been bugfixed to 0.5.0, but because these are 0.y.z releases the upgrade from 0.4.x to 0.5.0 is considered a major release and the ^ won't allow that and thus npm and yarn refuse to use that 0.5.0.

The thing is the 0.5.0 cldrjs contains an important bugfix that we need and now I'm forced to tweak that from our lock files and force the 0.5.0 there. It would be nice if there was a better resolution to this.

The cldrjs should have been bug fixed to version 0.4.9 to begin with!

**Comment by basex** [comment]
You created the Issue on the wrong project. The npm package is here https://github.com/globalizejs/globalize

**Comment by Kynde** [comment]
So true, sorry.
