### ISSUE TITLE
Serializing translated columns

### ISSUE THREAD

**Issue by jonhue** [globalize/globalize#673]
How are you supposed to serialize a translated attribute as an array?

Here is my setup:

```ruby
class Recipe < ApplicationRecord
  translate :titles
  serialize :titles, Array
end
```

Calling `recipe.titles` however returns a string.

**Comment by shawila** [comment]
As I mentioned [here](https://github.com/globalize/globalize/issues/53), this worked fine for me after I added `translation_class.send :serialize, :titles`, this worked fine for me (my case was for `Hash` instead of `Array`).

**Comment by jonhue** [comment]
```ruby
class Model    
  serialize :conditions, Array
  translates :title, :conditions
  translation_class.send :serialize, :conditions

  # etc
end
```

This is my code. I confirmed that it does not work -> I repeatedly get the following exception:

> undefined method `any?' for "[\"'s_0 = 0'\", \"'v_0 = 0'\"]":String`

when interpreting the `conditions` attribute as an array.

**Comment by jonhue** [comment]
It just started working, I haven't changed anything - just reseeded my database... Gotta close this.
