### ISSUE TITLE
Globalize does not allow Rails 5.2

### ISSUE THREAD

**Issue by damienlethiec** [globalize/globalize#676]
Hello,

I have launched a new rails 5.2 project today. Unfortunately, globalize still cannot be added to a rails 5.2 project as it depends on 'activerecord (< 5.2, >= 4.2)', even in the master branch.

Could you please update the gemspec of the master branch so we can try globalize against rails 5.2 ? 

Thanks a ton :)

My gem versions:
gem 'activerecord', '5.2.0'
gem 'globalize', git: 'https://github.com/globalize/globalize'

**Comment by ma3tk** [comment]
Same here.

**Comment by morgoth** [comment]
Can we have a release with 5.2.0 support, please?

**Comment by alhafoudh** [comment]
FYI https://www.bountysource.com/issues/56867925-globalize-does-not-allow-rails-5-2

**Comment by alhafoudh** [comment]
Yes they are but tests are failing

**Comment by bunyan** [comment]
Seems to be working now with Rails 5.2 and 
`gem 'globalize', git: 'https://github.com/globalize/globalize'`

**Comment by rhymes** [comment]
@bunyan yes, they merged https://github.com/globalize/globalize/pull/678
