### ISSUE TITLE
Fallback is not working for default locale

### ISSUE THREAD

**Issue by MatteoMat27** [globalize/globalize#682]
'activerecord', '5.0.7'
'globalize', '5.1.0'
'globalize_accessor', '0.2.1'
'rails', '5.0.7'

As the title says, fallback are only working for default locale. Eg. My availables locale are [:fr, :en], my default locale is :fr.If I enter the :fr title and leave the :en title blank and switch the current_locale for :en, the title will fallback to :fr since there is no :en translation. The other way around is not working. If I only enter a :en title and the default locale is :fr, there will be no fallback when I switch the current locale to :fr.

I have this line in application.rb:     config.i18n.fallbacks = true
This line in my model:     translates :name, fallbacks_for_empty_translations: true
Even tried adding this line in my model:   Globalize.fallbacks = {:en => [:en, :fr], :fr => [:fr, :en]}

**Comment by saiqulhaq** [comment]
in my rails 4 app
it seems the config on application.rb overriden by another gem/xxx, i don't know

so I have to create an initializer file with following content

```
require 'globalize'

Globalize.fallbacks = {
  ko: %i[ko en],
  en: %i[en th],
  th: %i[th en]
}
```

**Comment by MatteoMat27** [comment]
@saiqulhaq I dont see how it could be overwritten by another gem since to be sure I added it in my model. Tried it in an initializer with no luck.

**Comment by MatteoMat27** [comment]
For those having the same issue, I temporally fixed it overwritting the getter in the model.

```
  def name
    if self[:name].nil?
      globalize_attribute_names.each do |attribute|
        return self.send(attribute) unless self.send(attribute).blank?
      end
    else
      self[:name]
    end
  end
```

**Comment by DaniG2k** [comment]
+1 fallbacks aren't working for me either.

```
I18n.locale = :en
Post.first.title
=> "Post title"

I18n.locale = :it
Post.first.title
=> nil
```

In my `application.rb` I have:

```
config.i18n.default_locale = :en
config.i18n.fallbacks = true
```

**Comment by saiqulhaq** [comment]
@DaniG2k make sure that `title` attribute has Italian translation on database

on my app I use globalize_accessors gem, so I can check it easily using `Post.first.title_it` from my rails console without checking manually the database

**Comment by saiqulhaq** [comment]
oh yea sorry I misread your comment

**Comment by denisoster** [comment]
+1 fallbacks does not work in Rails 5.2.1

**Comment by carlesjove** [comment]
In Rails 5.2 I solved this by setting the fallbacks directly on `I18n`:

```ruby
# config/application.rb

config.i18n.fallbacks = {
  ca: [:ca, :es, :en],
  es: [:es, :ca, :en],
  en: [:en, :es, :ca],
}
```

**Comment by timpalander** [comment]
I'm having similar issues - but only in our production/staging environment, and only in the controller/view context (in the console it works as expected everywhere). In my local environment everything is working as expected. Activerecord 3.2 and Globalize 3.1.

![translation_fallback](https://user-images.githubusercontent.com/30126/46608237-60d9e300-cb04-11e8-86a5-c62cea701caf.jpg)

**Comment by PragmaticEd** [comment]
Any update on this?

**Comment by timpalander** [comment]
I ended up making my own fallback method for now that just loops through my list of languages in a preferred fallback priority order and returns the first found value.

`
# Create fallback method for each attribute you have globalized.
# I use this method when printing the title later, to keep the original 'title' intact for now.
def title_fallback
  lang_attr_fallback(:title)
end

private

def languages
  # Make a list of languages how you prefere it.
  [:en, :sv, :de, :fi, :nb]
end

def lang_attr_fallback(attribute)
  if try(attribute.to_sym).blank?
    languages.each do |language|
      value = try("#{attribute}_#{language}".to_sym)
      return value unless value.blank?
    end
    return ''
  else
    try(attribute.to_sym)
  end
rescue => e
  # handle exception
  return ''
end
`

**Comment by timpalander** [comment]
I ended up making my own fallback method for now that just loops through my list of languages in a preferred fallback priority order and returns the first found value.

```ruby
# Create fallback method for each attribute you have globalized.
# I use this method when printing the title later, to keep the original 'title' intact for now.
def title_fallback
  lang_attr_fallback(:title)
end

private

def languages
  # Make a list of languages how you prefere it.
  [:en, :sv, :de, :fi, :nb]
end

def lang_attr_fallback(attribute)
  if try(attribute.to_sym).blank?
    languages.each do |language|
      value = try("#{attribute}_#{language}".to_sym)
      return value unless value.blank?
    end
    ''
  else
    try(attribute.to_sym)
  end
rescue => e
  # handle exception
  ''
end

**Comment by PragmaticEd** [comment]
@timpalander This needs to be fixed, this isn't a good fix.. :(

**Comment by timpalander** [comment]
I know it's not ideal, but i had to make it work for now.

**Comment by PragmaticEd** [comment]
@carlesjove  Yes, and it had absolutely no effect.

@timpalander i made concern for myself, similar to your code. Maybe someone finds it useful:


```ruby
##TODO: remove this dirty fix when globalize fixes callback: https://github.com/globalize/globalize/issues/682
##
## Usage:
##
## class Post < ApplicationRecord
##    include GlobalizeFallbackFix
##
##   translates     :profession_name, :name, :slug, fallbacks_for_empty_translations: true
##   translates_fix :profession_name, :name, :slug
##   globalize_accessors locales: I18n.available_locales, attributes: [:name, :slug]
##
## end
##
require 'active_support/concern'

module GlobalizeFallbackFix
  extend ActiveSupport::Concern

  module ClassMethods

    def translates_fallback_fix(*attrs)
      attrs.each do |attr|
        define_method attr do
          value = self.send("#{attr}_#{I18n.locale}")

          language_fallback_order = {
            lv: [:lv, :en, :ru],
            en: [:en, :lv, :ru],
            ru: [:ru, :lv, :en]
          }

          language_fallback_order[I18n.locale.to_sym].each do |locale|
            value = self.send("#{attr}_#{locale}") if value.to_s.blank?
          end

          value
        end
      end
    end

  end
end

```

**Comment by timpalander** [comment]
> @timpalander @PragmaticEd Have any of you tried [this](https://github.com/globalize/globalize/issues/682#issuecomment-426606205) which I mention above?

I might have to take the walk of shame here. I found a specific environment setting overriding config.i18n.fallbacks, setting it to true. Still testing it but it seems to work for me now.

Sorry!

**Comment by PragmaticEd** [comment]
@timpalander so, if it works for you, that means something in my environment is overwriting that config. Guess i will have to have some debugging to do.. Thanks for feedback.

**Comment by timpalander** [comment]
It does indeed work for me now in both my development and staging environment. So yes, that's a likely case. Hope you find it, good luck!

**Comment by cheerfulstoic** [comment]
I found a simple solution which seems to work for us in the linked pull request ( #415 ).  All that I had to do was change `config.i18n.fallbacks = true` to `config.i18n.fallbacks = [:en]`

**Comment by cheerfulstoic** [comment]
Ah ha!  After linking to that PR, I got clarity around the `globalize` repo vs the `i18n` repo.  I was looking originally in the `globalize` changelog, but I see this very explicitly stated on the [releases page](https://github.com/svenfuchs/i18n/releases) for the `i18n` gem for version 1.1.0 of `i18n`.  That specifically directs you to do:

```ruby
config.i18n.fallbacks = [I18n.default_locale]
```

So that should hopefully make things work

**Comment by cheerfulstoic** [comment]
Made a documentation PR: https://github.com/globalize/globalize/pull/713

**Comment by PragmaticEd** [comment]
Yes, hence the reason it didn't work.. I had it saved from many projects back, without realizing, that the syntax was wrong, just like @VitaliyAdamkov stated.

Setting it to hash actually is the fix. Maybe this should be updated in docs now, so its easier to understand for new people.

**Comment by cheerfulstoic** [comment]
You can certainly set it to a Hash, but if you always want to fallback to a specific language or a series of subsequent languages then the `Array` is much simpler.  It's also what's recommended by the `i18n` gem

**Comment by fuuman** [comment]
This issue is still not solved. 
Solution of @carlesjove is unfortunately not working for me.
