### ISSUE TITLE
Rails 5.2 error with adapter_dirty.rb 

### ISSUE THREAD

**Issue by noccor** [globalize/globalize#683]
Hi,

When upgrading an application to rails 5.2. I found Globalize stopped working, specifically in the `_reset_attribute` method in the `active_record/adapter_dirty.rb` file. 

When updating records, `original_changed_attributes` is nil, so I receive the following error: 

`undefined method `except!' for nil:NilClass`

If I regress to rails 5.1 all works well. To get around this we've patched the `_reset_attribute` method, commenting out line 45, following this all seems to be working (on the surface at least):

```
43      def _reset_attribute name
44        record.send("#{name}=", record.changed_attributes[name])
45        # record.original_changed_attributes.except!(name)
46      end
```

I'm assuming this is to do with Rails 5.2. 

**Versions:** 
Rails: 5.2.0
Globalize: 5.1.0
ActiveRecord: 5.2.0

**Comment by basex** [comment]
Related https://github.com/globalize/globalize/pull/674

**Comment by noccor** [comment]
@basex I should of checked the PR before making this. Cheers!

**Comment by parndt** [comment]
Closing because #674 was merged - thanks!
