### ISSUE TITLE
update_attributes not working as expected

### ISSUE THREAD

**Issue by adamgrad** [globalize/globalize#684]
Hello,
I have found an issue where `update_attributes` is not working as expected for models with globalized attributes. For simple model (in my case Category) update_attributes with passed empty hash does not change anything, and the in the same scenario for model with globalized attributes (model Article) it does change `updated_at`.

Rails 5.0.7
Globalize 5.1.0
Repository where the issue has been reproduced in specs:
https://github.com/adamgrad/globalize-issue

**Comment by JulienItard** [comment]
Hello, i have exactly same issue. Any ideas ? Thanks !
