### ISSUE TITLE
In Rails 5.2 dont not insert the relation ID in set_translations method

### ISSUE THREAD

**Issue by ymalmaguer** [globalize/globalize#687]
# Activate the gem you are reporting the issue against.
rails 5.2.0
gem 'activerecord', '5.2.0'
gem 'globalize', master

When we call tha method set_translations whit some object not put the relation, example I have a model name Category and when I do:  
category.set_translations(translation_entity_params.to_h)
I have  something like this:
An ActiveRecord::NotNullViolation occurred in category#create: Mysql2::Error: Field 'category_id' doesn't have a default value: INSERT INTO `category_translations` (`locale`, `created_at`, `updated_at`, `service_terms`) VALUES ('es', '2018-05-31 13:59:35', '2018-05-31 13:59:35', '<p>category 1:Hi globalize</p>')

**Comment by basex** [comment]
I was having the same problem. I think it's similar to https://github.com/globalize/globalize/issues/685

See if this PR solves your problem https://github.com/globalize/globalize/pull/686

**Comment by ymalmaguer** [comment]
Thanks a lot. That fixed the problem.
