### ISSUE TITLE
Rails 5.x installation instructions not clear

### ISSUE THREAD

**Issue by ganlub** [globalize/globalize#691]
I'm on Rails 5.2 and I followed the installation section on the Readme, because I'm using bundler and I added `gem 'globalize', '~> 5.1.0'` in my Gem file. I got the following error:
```
Bundler could not find compatible versions for gem "activemodel":
  In snapshot (Gemfile.lock):
    activemodel (= 5.2.0)

  In Gemfile:
    globalize (~> 5.1.0) was resolved to 5.1.0, which depends on
      activemodel (< 5.2, >= 4.2)

    rails (~> 5.2.0) was resolved to 5.2.0, which depends on
      activemodel (= 5.2.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

After some digging I found #527 and #533. The indication on the Readme about Rails 5.x is gone:

![image](https://user-images.githubusercontent.com/1272617/42363660-b77baf46-80f8-11e8-9c7a-fa5225e2bfb2.png)

**Comment by corselia** [comment]
the very same problem occurs for me. thanks your issue!
my case is below (`Rails 5.2.0`). 

first, added `gem 'globalize', '~> 5.1.0'` to `Gemfile` and `bundle install` but the dependency error occurs. so executed `bundle update`. and it looks successful.

however `bundle exec unicorn` causes error as below.

```
E, [2018-07-25T17:55:14.240831 #28314] ERROR -- : Unknown version "5.2" (RuntimeError)
```

so I removed `Gemfile.lock` file and `gem 'globalize', '~> 5.1.0'` from `Gemfile`, and `bundle install` (revert).

in the next, added two lines as below to `Gemfile` and `bundle install`

```ruby
gem 'globalize', git: 'https://github.com/globalize/globalize'
gem 'activemodel-serializers-xml'
```

so `bundle exec unicorn` was executed correctly :)
