### ISSUE TITLE
Allow Validators to be Run Against Translation Tables

### ISSUE THREAD

**Issue by Tresky** [globalize/globalize#692]
I am currently using Active Record 5.0.6 and Globalize 5.1.0.beta.

I am trying to set up validators to run on `MyClass::Translation` whenever a record is updated. My table has two columns that are filled out based on another column. So, the validator need to run when that column is updated so the other two get their values set.

Anyone know if there is an accepted solution for this?

I've tried the following, but it doesn't see to ever execute the validators:
```
class MyClass
    translates :parent_field, :child_field_a, :child_field_b

    # Tried it with the inheritance and without it
    class Translation # < Globalize::ActiveRecord::Translation
        before_validation :fillout_fields
        def fillout_fields
            # do the stuff
        end
    end
end
```

**Comment by microweb10** [comment]
@Tresky any news on this?
