### ISSUE TITLE
Rails 5.2 Attribute's type is missing

### ISSUE THREAD

**Issue by nicovak** [globalize/globalize#693]
Hello,

With the **master** branch and **rails 5.2**, attribute type of the model are not present anymore.
Example of a model `Post` with `title` translated.

If you run in the console `Post.inspect` the type for `title` is blank.

```
Post(id: integer, title: )
```

Same thing with this method : `type_for_attribute` from [Rails doc](http://api.rubyonrails.org/classes/ActiveRecord/ModelSchema/ClassMethods.html#method-i-type_for_attribute)

as described : 

> This method is the only valid source of information for anything related to the types of a model's attributes.

```ruby
Post.type_for_attribute(:title)
```

If you do so, you will have 

```
#<ActiveModel::Type::Value:0x00007f914b599f28 @limit=nil, @precision=nil, @scale=nil>
```

It was working with Rails 5.1

**Comment by lazyatom** [comment]
Related to #611

**Comment by lazyatom** [comment]
I have probably covered this in [my comment](https://github.com/globalize/globalize/issues/611#issuecomment-476769255) on #611, but in a nutshell you may be able to get around this by declaring your types using the attribute API on both the base class and the translation class.
