### ISSUE TITLE
The name Translation is too generic, we should namespace it

### ISSUE THREAD

**Issue by myxoh** [globalize/globalize#695]
In a project I'm working on, I  am using Globalize por parts of it, but the fact that the module is an un-namespaced module called Translation is causing name conflicts on a new service we are trying to integrate with the project.

It'd be awesome if we, instead, called the module Globalize::Translation (or something like that) to prevent this sort of conflicts.

If I have the time I'll issue a PR, but please do let me know if this is something you'd be open to, as changing all the references might not e that simple

# Activate the gem you are reporting the issue against.
gem 'activerecord', '4.0.0'
gem 'globalize', '5.0.1'
require 'active_record'
require 'globalize'
require 'minitest/autorun'
require 'logger'

# Ensure backward compatibility with Minitest 4
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
  end

  create_table :post_translations, force: true do |t|
    t.references :post
    t.string     :title
    t.text       :content
    t.string     :locale
  end
end

class Post < ActiveRecord::Base
  translates :content, :title
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!(title: 'HI')

    assert_equal 'HI', post.title
  end
end

**Comment by tomash** [comment]
This sounds like a good idea. Would you like to make a PR?

**Comment by myxoh** [comment]
Hi @tomash sorry for taking this long to respond. I'll happily write a PR as soon as I have time to re-focus on this. It might take another couple of weeks.

**Comment by giedriusr** [comment]
Sounds like a good idea! 👍
