### ISSUE TITLE
rails 5.2 deprecation warning

### ISSUE THREAD

**Issue by wongy91** [globalize/globalize#706]
`gem 'globalize', github: 'globalize/globalize', ref: 'ff22b92bfa283bb9f378899031dbfad38de6280d'`

DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "\"friendly_id_slugs\".id DESC". Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql(). (called from with_locale at /Users/.../.../versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/globalize-ff22b92bfa28/lib/globalize.rb:27)

**Comment by teoljungberg** [comment]
I have the same issue, and I expected the release of v5.2.0 in https://github.com/globalize/globalize/commit/4702dc861ca662c50331fc8734cc6f682c0508db  to have resolved the deprecation warning.

**Comment by parndt** [comment]
Does this really still happen with version 5.2.0?

**Comment by teoljungberg** [comment]
@parndt 

Based on what I can see in our application, yes:

```
% grep globalize Gemfile
gem 'globalize', '~> 5.2'
```

I'd like to find a minimum reproduction case somehow, do we have one?
