### ISSUE TITLE
dynamic attributes incorrectly returned as nil

### ISSUE THREAD

**Issue by shushugah** [globalize/globalize#716]
We had bug introduced when upgrading from `globalize 4.0.3` to `globalize 5.2.0`. 

we have a `color_structure` model which looks like the following
```ruby
ColorStructure < ActiveRecord::Base # rails 4.1
### 
  translates :title, fallbacks_for_empty_translations: true
  globalize_accessors locales: Country::TRANSLATED_LANGUAGES, attributes: [:title]
```

and we accessed it's title in associated objects via `color_structure.try(:title)` which now return 
`nil`. As a work around (we use ruby 2.3+) we could use `color_structure&.title` instead which correctly returned values. Any idea why?

**Comment by meinac** [comment]
The problem in essence is, `object.respond_to?(:title)` returns `true` at version 4.0.3 and `false` at version 5.2.0.

**Comment by meinac** [comment]
I made some investigation on this, seems like #711 solves the problem. Is there a plan for making a release with that fix in the near future?
