### ISSUE TITLE
Disable auto translation loading

### ISSUE THREAD

**Issue by sikandartariq1** [globalize/globalize#730]
Can we disable translation loading for specific queries where we do not need translations?
For example:
 `[Modal].first` or `[Model].where(name: 'abc')`
**Two queries will be executed** 
`select * from tabel_name` 
`select * from tabel_name_translations where ...`
but in some cases we do not need second query to be executed (e.g we are not going to use any attribute which we have translated)

I think something like this would be great to optimize query structure.
`Model.without_transltions.first`
`Model.without_transltions.where(name: 'abc')`

**Comment by abdulbasit1248** [comment]
+1

**Comment by ext-skumark** [comment]
It is really required, Is anyone working on this?

**Comment by sikandartariq1** [comment]
@ext-skumark motivating myself to give it a try on my own.

**Comment by giedriusr** [comment]
Is there maybe a way to skip loading translations with smth like `.unscoped`? Trying this didn't work.

**Comment by harshaljain27** [comment]
Has anyone found out a solution to this ?
