### ISSUE TITLE
`add_translation_fields!` does not migrate data

### ISSUE THREAD

**Issue by yboulkaid** [globalize/globalize#745]
When migrating existing fields from the model into the translation table,
the newly created fields are all `nil`.

Example:
```ruby
# Before migration:
class Post < ApplicationRecord
  translates :title

  # `body` attribute is not translated
end

Post.find(1).body
# => 'Untranslated body' 

# Migrating `body` to being translated:
class Post < ApplicationRecord
  translates :title, :body
end

# In the migration:
Post.add_translation_fields!(
  {
    body: :text,
  },
  migrate_data: true
)

Post.find(1).body
# => nil
```

After some digging, I think it comes from the [call to `read_attribute`](https://github.com/globalize/globalize/blob/master/lib/globalize/active_record/migration.rb#L145) during the data migration. It seems that instead of returning the raw data from the column, it returns `nil`. Even [the call to ActiveRecord's `_read_attribute`](https://github.com/globalize/globalize/blob/master/lib/globalize/active_record/instance_methods.rb#L70) returns `nil` 🤔 

For now we have to run the data migrations manually:
```ruby
  def up
    add_column :post_translations, :body, :string

    Post.find_each do |post|
      translation = post.translation_for(:en)
      translation.update!(body: post.body)
    end
  end

  def down
    remove_column :post_translations, :body
  end
```

This is using:
- `globalize 5.3.0`
- `rails 6.0.2.1`

**Comment by schmijos** [comment]
@yboulkaid be aware that your `down`-migration doesn't migrate any data back.

**Comment by Sefux** [comment]
Hi, 
I was struggling with this behaviour also. And for me @yboulkaid solution did not solve the issue of data lose (actually your data is never lost, if you do not remove the old untranslated field). 
I think the problem relates to rails ORM magic. 
At the time of our migration the model is already using the "new" translation mechanism (so post.body is returning the empty translation). 
To work around this, i had to disable the model attribute in the translates statement (before migration state), run the migration and fix the model again.  

`bundle exec rails db:migrate:down VERSION=2023xxx`

```ruby
class Post < ApplicationRecord
  translates :title #, :body 

  # body attribute is commented out
end
```

`bundle exec rails db:migrate:up VERSION=2023xxx`

```ruby
class Post < ApplicationRecord
  translates :title, :body 

  # body attribute is commented back in
end
```
