### ISSUE TITLE
is there breaking changes for v6?

### ISSUE THREAD

**Issue by saiqulhaq** [globalize/globalize#779]
https://github.com/globalize/globalize/releases/tag/v6.0.0

Sorry I just noticed that v6 is released
is there explanation why there is major version upgrade?

**Comment by parndt** [comment]
Here's the changelog: https://github.com/globalize/globalize/blob/master/CHANGELOG.md#600-2021-01-11

Nothing particularly majorly breaking but we tend to keep it sort of in-sync with Rails' version numbers.
